# Conceitos básicos sobre manipulação de dados

## Tipos de dados

### Dados estruturados vs Não estruturados

![Dados](\imagem01.webp)


## Pacotes usados neste Notebook

In [42]:
# Pacotes usados neste notebook
import pandas as pd

## Manipulação de Dados com Pandas

### 1. Manipulação Básica de Datasets



Dataset: Gas Prices in Brazil: https://www.kaggle.com/matheusfreitag/gas-prices-in-brazil

Este dataset contém os registros dos preços médios semanais dos combustíveis do Brasil entre os anos de 2004 e 2019.
Cada observação (registro/linha) consiste em um registro de preço aferido para um dado tipo de combustível em uma dada localidade do Brasil.
Alguns dos principais atributos (colunas) do dataset são: 'ESTADO', 'PRODUTO', 'NÚMERO DE POSTOS PESQUISADOS', 'PREÇO MÉDIO REVENDA'.



#### 1.1 Importando o Dataset

Para carregar um dataset no formato csv, basta utilizar a função read_csv do pandas. Por padrão, ela considera ',' como separador.

In [43]:
data = pd.read_csv('./datasets/Preco_Combustiveis.csv', sep=';')

In [44]:
data

Unnamed: 0 DATA INICIAL  DATA FINAL        REGIÃO  \
0                0   2004-05-09  2004-05-15  CENTRO OESTE   
1                1   2004-05-09  2004-05-15  CENTRO OESTE   
2                2   2004-05-09  2004-05-15  CENTRO OESTE   
3                3   2004-05-09  2004-05-15  CENTRO OESTE   
4                4   2004-05-09  2004-05-15      NORDESTE   
...            ...          ...         ...           ...   
106818      106818   2019-06-23  2019-06-29      NORDESTE   
106819      106819   2019-06-23  2019-06-29           SUL   
106820      106820   2019-06-23  2019-06-29           SUL   
106821      106821   2019-06-23  2019-06-29       SUDESTE   
106822      106822   2019-06-23  2019-06-29      NORDESTE   

                     ESTADO           PRODUTO  NÚMERO DE POSTOS PESQUISADOS  \
0          DISTRITO FEDERAL  ETANOL HIDRATADO                           127   
1                     GOIAS  ETANOL HIDRATADO                           387   
2               MATO GROSSO  ETANOL HIDRATADO                           192   
3        MATO GROSSO DO SUL  ETANOL HIDRATADO                           162   
4                   ALAGOAS  ETANOL HIDRATADO                           103   
...                     ...               ...                           ...   
106818  RIO GRANDE DO NORTE               GNV                             7   
106819    RIO GRANDE DO SUL               GNV                            23   
106820       SANTA CATARINA               GNV                            24   
106821            SAO PAULO               GNV                            52   
106822              SERGIPE               GNV                             4   

       UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  ...  \
0                   R$/l                1.288                  0.016  ...   
1                   R$/l                1.162                  0.114  ...   
2                   R$/l                1.389                  0.097  ...   
3                   R$/l                1.262                  0.070  ...   
4                   R$/l                1.181                  0.078  ...   
...                  ...                  ...                    ...  ...   
106818             R$/m3                3.574                  0.065  ...   
106819             R$/m3                3.401                  0.129  ...   
106820             R$/m3                2.912                  0.190  ...   
106821             R$/m3                3.020                  0.229  ...   
106822             R$/m3                3.697                  0.005  ...   

        PREÇO MÁXIMO REVENDA  MARGEM MÉDIA REVENDA COEF DE VARIAÇÃO REVENDA  \
0                      1.350                 0.463                    0.012   
1                      1.449                 0.399                    0.098   
2                      1.760                 0.419                    0.070   
3                      1.509                 0.432                    0.055   
4                      1.400                  0.24                    0.066   
...                      ...                   ...                      ...   
106818                 3.690                 0.818                    0.018   
106819                 3.789                  0.95                    0.038   
106820                 3.499                 0.914                    0.065   
106821                 3.490                 0.646                    0.076   
106822                 3.699                 1.179                    0.001   

        PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                          0.825                       0.11   
1                          0.763                      0.088   
2                           0.97                      0.095   
3                           0.83                      0.119   
4                          0.941                      0.077   
...                          ...                        ...   
106818     

#### 1.2 Exibindo as primeiras linhas

A função .head() exibe as 5 primeiras linhas do dataset/tabela/Data Frame.

In [45]:
data.head()

Unnamed: 0 DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0           0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1           1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2           2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3           3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4           4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  ...  PREÇO MÁXIMO REVENDA  \
0                1.288                  0.016  ...                 1.350   
1                1.162                  0.114  ...                 1.449   
2                1.389                  0.097  ...                 1.760   
3                1.262                  0.070  ...                 1.509   
4                1.181                  0.078  ...                 1.400   

   MARGEM MÉDIA REVENDA COEF DE VARIAÇÃO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO  \
0                 0.463                    0.012                     0.825   
1                 0.399                    0.098                     0.763   
2                 0.419                    0.070                      0.97   
3                 0.432                    0.055                      0.83   
4                  0.24                    0.066                     0.941   

  DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                       0.11                    0.4201   
1                      0.088                    0.5013   
2                      0.095                    0.5614   
3                      0.119                    0.5991   
4                      0.077                    0.7441   

  PREÇO MÁXIMO DISTRIBUIÇÃO COEF DE VARIAÇÃO DISTRIBUIÇÃO MÊS   ANO  
0                    0.9666                         0.133   5  2004  
1                      1.05                         0.115   5  2004  
2                     1.161                         0.098   5  2004  
3                   1.22242                         0.143   5  2004  
4                    1.0317                         0.082   5  2004  

[5 rows x 21 columns]

#### 1.3 Informações do Dataset e Elementos Chave

##### 1.3.1 Informações gerais sobre o Dataset

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   Unnamed: 0                     106823 non-null  int64  
 1   DATA INICIAL                   106823 non-null  object 
 2   DATA FINAL                     106823 non-null  object 
 3   REGIÃO                         106823 non-null  object 
 4   ESTADO                         106823 non-null  object 
 5   PRODUTO                        106823 non-null  object 
 6   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64  
 7   UNIDADE DE MEDIDA              106823 non-null  object 
 8   PREÇO MÉDIO REVENDA            106823 non-null  float64
 9   DESVIO PADRÃO REVENDA          106823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           106823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 12  MARGEM MÉDIA REVENDA          

##### 1.3.2 Data Frame

Todo dataser carregado (dados estruturados) é um **Data Frame**: 'Tabela'bi-dimensional, de tamanho mutável, com dados potencialmente heterogêneos.

In [47]:
type(data)

pandas.core.frame.DataFrame

Podemos acessar as dimensões do **Data Frame** ( número de linhas x número de colunas) utilizando o atributo **.shape** do Data Frame

In [48]:
data.shape

(106823, 21)

In [49]:
print(f'O DataFrame possui {data.shape[0]} linhas/observaçòes/registro e {data.shape[1]} colunas/atributos.variáveis.')

O DataFrame possui 106823 linhas/observaçòes/registro e 21 colunas/atributos.variáveis.


##### Criando um DataFrame

- Podemos criar um DataFrame a partir de um dicionário, onde cada **chave** possui uma **lista de elementos de igual tamanho**.
- As **chaves** representam as **colunas** e **cada um dos valores de sua lista** representa o **valor da linha** correspondente para aquela coluna.

In [50]:
personagens_df = pd.DataFrame({
    'nome': ['Luke Skywalker', 'Yoda', 'Palpatine'],
    'idade': [16, 1000, 70],
    'peso': [70.5, 15.2, 60.1],
    'eh jedi': [True, True, False]
})

In [51]:
personagens_df

nome  idade  peso  eh jedi
0  Luke Skywalker     16  70.5     True
1            Yoda   1000  15.2     True
2       Palpatine     70  60.1    False

In [52]:
personagens_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   nome     3 non-null      object 
 1   idade    3 non-null      int64  
 2   peso     3 non-null      float64
 3   eh jedi  3 non-null      bool   
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 203.0+ bytes


##### Renomeando as colunas de um DataFrame
- O método `DataFrame.columns` retorna uma "lista" com os **nomes de todas as colunas** do data frame.

In [53]:
personagens_df.columns

Index(['nome', 'idade', 'peso', 'eh jedi'], dtype='object')

In [54]:
type(personagens_df.columns)

pandas.core.indexes.base.Index

In [55]:
list(personagens_df.columns)

['nome', 'idade', 'peso', 'eh jedi']

- Para **renomear colunas** do data frame, utilize o método `DataFrame.rename`, que retornar uma cópia do data frame com as colunas renomeadas:

In [56]:
personagens_df_renomaeado = personagens_df.rename(columns={
    'nome': 'Nome Completo',
    'idade': 'Idade'
})

In [57]:
personagens_df.rename(columns={
    'nome': 'Nome Completo',
    'idade': 'Idade'
}, inplace=True)

In [58]:
personagens_df

Nome Completo  Idade  peso  eh jedi
0  Luke Skywalker     16  70.5     True
1            Yoda   1000  15.2     True
2       Palpatine     70  60.1    False

- Uma outra forma de **renomear todas as colunas** de um data frame é passar uma lista com os novos nomes das colunas para o atributo `DataFrame.columns`:

In [59]:
personagens_df.columns

Index(['Nome Completo', 'Idade', 'peso', 'eh jedi'], dtype='object')

In [60]:
personagens_df.columns = ['NOME', 'IDADE', 'PESO', 'EH_JEDI']

In [61]:
personagens_df

NOME  IDADE  PESO  EH_JEDI
0  Luke Skywalker     16  70.5     True
1            Yoda   1000  15.2     True
2       Palpatine     70  60.1    False

##### 1.3.3 Series

- Array uni-demensinal com os dados e rótulos de um eixo.

In [62]:
data.head()

Unnamed: 0 DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0           0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1           1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2           2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3           3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4           4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  ...  PREÇO MÁXIMO REVENDA  \
0                1.288                  0.016  ...                 1.350   
1                1.162                  0.114  ...                 1.449   
2                1.389                  0.097  ...                 1.760   
3                1.262                  0.070  ...                 1.509   
4                1.181                  0.078  ...                 1.400   

   MARGEM MÉDIA REVENDA COEF DE VARIAÇÃO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO  \
0                 0.463                    0.012                     0.825   
1                 0.399                    0.098                     0.763   
2                 0.419                    0.070                      0.97   
3                 0.432                    0.055                      0.83   
4                  0.24                    0.066                     0.941   

  DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                       0.11                    0.4201   
1                      0.088                    0.5013   
2                      0.095                    0.5614   
3                      0.119                    0.5991   
4                      0.077                    0.7441   

  PREÇO MÁXIMO DISTRIBUIÇÃO COEF DE VARIAÇÃO DISTRIBUIÇÃO MÊS   ANO  
0                    0.9666                         0.133   5  2004  
1                      1.05                         0.115   5  2004  
2                     1.161                         0.098   5  2004  
3                   1.22242                         0.143   5  2004  
4                    1.0317                         0.082   5  2004  

[5 rows x 21 columns]

In [63]:
# Selecionando uma coluna inteira.
data['ESTADO'] 

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...         
106818    RIO GRANDE DO NORTE
106819      RIO GRANDE DO SUL
106820         SANTA CATARINA
106821              SAO PAULO
106822                SERGIPE
Name: ESTADO, Length: 106823, dtype: object

In [64]:
# Selecionando uma coluna inteira.
# Esta forma de acesso, só funciona para colunas com nomes sem espaços, acentos, etc(caracteres inválidos).
data.ESTADO 

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...         
106818    RIO GRANDE DO NORTE
106819      RIO GRANDE DO SUL
106820         SANTA CATARINA
106821              SAO PAULO
106822                SERGIPE
Name: ESTADO, Length: 106823, dtype: object

In [65]:
# Selecionando a observação indexada no índice [1] do DataFrame.

data.iloc[1]

Unnamed: 0                                      1
DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
MÊS                                             5


###### Criando uma Series

In [66]:
pd.Series([5.5, 6.0,7.0])

0    5.5
1    6.0
2    7.0
dtype: float64

##### 1.3.4 Atribuindo Dados

- 1.3.4.1 Atribuindo constantes

In [67]:
produto_view = data['PRODUTO'] # a series retornada referente à coluna, NÃO É UMA CÓPIA, mas sim, uma REFERÊNCIAS/VIEW à coluna do dataframe.
produto_view

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...       
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

In [68]:
produto_copy_bkp = data['PRODUTO'].copy() # Retorna uma cópia da coluna 'PRODUTO'
produto_copy_bkp

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...       
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

In [69]:
data['PRODUTO'] = 'Combustível' # Atribuindo o valor constante `Combustível` para cada linha do dataframe na coluna `PRODUTO`

In [70]:
data.head()

Unnamed: 0 DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0           0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1           1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2           2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3           3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4           4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

       PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  Combustível                           127              R$/l   
1  Combustível                           387              R$/l   
2  Combustível                           192              R$/l   
3  Combustível                           162              R$/l   
4  Combustível                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  ...  PREÇO MÁXIMO REVENDA  \
0                1.288                  0.016  ...                 1.350   
1                1.162                  0.114  ...                 1.449   
2                1.389                  0.097  ...                 1.760   
3                1.262                  0.070  ...                 1.509   
4                1.181                  0.078  ...                 1.400   

   MARGEM MÉDIA REVENDA COEF DE VARIAÇÃO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO  \
0                 0.463                    0.012                     0.825   
1                 0.399                    0.098                     0.763   
2                 0.419                    0.070                      0.97   
3                 0.432                    0.055                      0.83   
4                  0.24                    0.066                     0.941   

  DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                       0.11                    0.4201   
1                      0.088                    0.5013   
2                      0.095                    0.5614   
3                      0.119                    0.5991   
4                      0.077                    0.7441   

  PREÇO MÁXIMO DISTRIBUIÇÃO COEF DE VARIAÇÃO DISTRIBUIÇÃO MÊS   ANO  
0                    0.9666                         0.133   5  2004  
1                      1.05                         0.115   5  2004  
2                     1.161                         0.098   5  2004  
3                   1.22242                         0.143   5  2004  
4                    1.0317                         0.082   5  2004  

[5 rows x 21 columns]

In [71]:
produto_view

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...       
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

In [72]:
produto_copy_bkp

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...       
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

- 1.3.4.2 Atribuindo listas ou series

In [73]:
nrows, ncols = data.shape
nrows, ncols

(106823, 21)

In [74]:
novos_produtos = [f'Produto {i}' for i in range(nrows)]
len(novos_produtos)

106823

In [75]:
data['PRODUTO'] = novos_produtos # a quantidade de elementos da lista `novos_produtos` é igual ao número de linhas do dataframe.


In [76]:
data

Unnamed: 0 DATA INICIAL  DATA FINAL        REGIÃO  \
0                0   2004-05-09  2004-05-15  CENTRO OESTE   
1                1   2004-05-09  2004-05-15  CENTRO OESTE   
2                2   2004-05-09  2004-05-15  CENTRO OESTE   
3                3   2004-05-09  2004-05-15  CENTRO OESTE   
4                4   2004-05-09  2004-05-15      NORDESTE   
...            ...          ...         ...           ...   
106818      106818   2019-06-23  2019-06-29      NORDESTE   
106819      106819   2019-06-23  2019-06-29           SUL   
106820      106820   2019-06-23  2019-06-29           SUL   
106821      106821   2019-06-23  2019-06-29       SUDESTE   
106822      106822   2019-06-23  2019-06-29      NORDESTE   

                     ESTADO         PRODUTO  NÚMERO DE POSTOS PESQUISADOS  \
0          DISTRITO FEDERAL       Produto 0                           127   
1                     GOIAS       Produto 1                           387   
2               MATO GROSSO       Produto 2                           192   
3        MATO GROSSO DO SUL       Produto 3                           162   
4                   ALAGOAS       Produto 4                           103   
...                     ...             ...                           ...   
106818  RIO GRANDE DO NORTE  Produto 106818                             7   
106819    RIO GRANDE DO SUL  Produto 106819                            23   
106820       SANTA CATARINA  Produto 106820                            24   
106821            SAO PAULO  Produto 106821                            52   
106822              SERGIPE  Produto 106822                             4   

       UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  ...  \
0                   R$/l                1.288                  0.016  ...   
1                   R$/l                1.162                  0.114  ...   
2                   R$/l                1.389                  0.097  ...   
3                   R$/l                1.262                  0.070  ...   
4                   R$/l                1.181                  0.078  ...   
...                  ...                  ...                    ...  ...   
106818             R$/m3                3.574                  0.065  ...   
106819             R$/m3                3.401                  0.129  ...   
106820             R$/m3                2.912                  0.190  ...   
106821             R$/m3                3.020                  0.229  ...   
106822             R$/m3                3.697                  0.005  ...   

        PREÇO MÁXIMO REVENDA  MARGEM MÉDIA REVENDA COEF DE VARIAÇÃO REVENDA  \
0                      1.350                 0.463                    0.012   
1                      1.449                 0.399                    0.098   
2                      1.760                 0.419                    0.070   
3                      1.509                 0.432                    0.055   
4                      1.400                  0.24                    0.066   
...                      ...                   ...                      ...   
106818                 3.690                 0.818                    0.018   
106819                 3.789                  0.95                    0.038   
106820                 3.499                 0.914                    0.065   
106821                 3.490                 0.646                    0.076   
106822                 3.699                 1.179                    0.001   

        PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                          0.825                       0.11   
1                          0.763                      0.088   
2                           0.97                      0.095   
3                           0.83                      0.119   
4                          0.941                      0.077   
...                          ...                        ...   
106818                     2.756   

In [77]:
data['PRODUTO'] = produto_copy_bkp # voltando para os produtos originais
data

Unnamed: 0 DATA INICIAL  DATA FINAL        REGIÃO  \
0                0   2004-05-09  2004-05-15  CENTRO OESTE   
1                1   2004-05-09  2004-05-15  CENTRO OESTE   
2                2   2004-05-09  2004-05-15  CENTRO OESTE   
3                3   2004-05-09  2004-05-15  CENTRO OESTE   
4                4   2004-05-09  2004-05-15      NORDESTE   
...            ...          ...         ...           ...   
106818      106818   2019-06-23  2019-06-29      NORDESTE   
106819      106819   2019-06-23  2019-06-29           SUL   
106820      106820   2019-06-23  2019-06-29           SUL   
106821      106821   2019-06-23  2019-06-29       SUDESTE   
106822      106822   2019-06-23  2019-06-29      NORDESTE   

                     ESTADO           PRODUTO  NÚMERO DE POSTOS PESQUISADOS  \
0          DISTRITO FEDERAL  ETANOL HIDRATADO                           127   
1                     GOIAS  ETANOL HIDRATADO                           387   
2               MATO GROSSO  ETANOL HIDRATADO                           192   
3        MATO GROSSO DO SUL  ETANOL HIDRATADO                           162   
4                   ALAGOAS  ETANOL HIDRATADO                           103   
...                     ...               ...                           ...   
106818  RIO GRANDE DO NORTE               GNV                             7   
106819    RIO GRANDE DO SUL               GNV                            23   
106820       SANTA CATARINA               GNV                            24   
106821            SAO PAULO               GNV                            52   
106822              SERGIPE               GNV                             4   

       UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  ...  \
0                   R$/l                1.288                  0.016  ...   
1                   R$/l                1.162                  0.114  ...   
2                   R$/l                1.389                  0.097  ...   
3                   R$/l                1.262                  0.070  ...   
4                   R$/l                1.181                  0.078  ...   
...                  ...                  ...                    ...  ...   
106818             R$/m3                3.574                  0.065  ...   
106819             R$/m3                3.401                  0.129  ...   
106820             R$/m3                2.912                  0.190  ...   
106821             R$/m3                3.020                  0.229  ...   
106822             R$/m3                3.697                  0.005  ...   

        PREÇO MÁXIMO REVENDA  MARGEM MÉDIA REVENDA COEF DE VARIAÇÃO REVENDA  \
0                      1.350                 0.463                    0.012   
1                      1.449                 0.399                    0.098   
2                      1.760                 0.419                    0.070   
3                      1.509                 0.432                    0.055   
4                      1.400                  0.24                    0.066   
...                      ...                   ...                      ...   
106818                 3.690                 0.818                    0.018   
106819                 3.789                  0.95                    0.038   
106820                 3.499                 0.914                    0.065   
106821                 3.490                 0.646                    0.076   
106822                 3.699                 1.179                    0.001   

        PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                          0.825                       0.11   
1                          0.763                      0.088   
2                           0.97                      0.095   
3                           0.83                      0.119   
4                          0.941                      0.077   
...                          ...                        ...   
106818     

- 1.3.4.3 Criando novas colunas

Para **criar uma nova coluna** em um data frame, basta atribuirmos uma _lista/Series de valores_ ou uma constrante a uma **nova 'chave'** do data frame.<br/>

**PS:** A_quantidade de valores_ da lista precisar ser **igual** ao _número de linhas/registros_ do data frame.

In [78]:
# Criando uma coluna a partir de um valor constante/default
# Todas as linhas terão o mesmo valor para esta nova coluna
data['colunar sem nocao'] = 'DEFAULT'
data

Unnamed: 0 DATA INICIAL  DATA FINAL        REGIÃO  \
0                0   2004-05-09  2004-05-15  CENTRO OESTE   
1                1   2004-05-09  2004-05-15  CENTRO OESTE   
2                2   2004-05-09  2004-05-15  CENTRO OESTE   
3                3   2004-05-09  2004-05-15  CENTRO OESTE   
4                4   2004-05-09  2004-05-15      NORDESTE   
...            ...          ...         ...           ...   
106818      106818   2019-06-23  2019-06-29      NORDESTE   
106819      106819   2019-06-23  2019-06-29           SUL   
106820      106820   2019-06-23  2019-06-29           SUL   
106821      106821   2019-06-23  2019-06-29       SUDESTE   
106822      106822   2019-06-23  2019-06-29      NORDESTE   

                     ESTADO           PRODUTO  NÚMERO DE POSTOS PESQUISADOS  \
0          DISTRITO FEDERAL  ETANOL HIDRATADO                           127   
1                     GOIAS  ETANOL HIDRATADO                           387   
2               MATO GROSSO  ETANOL HIDRATADO                           192   
3        MATO GROSSO DO SUL  ETANOL HIDRATADO                           162   
4                   ALAGOAS  ETANOL HIDRATADO                           103   
...                     ...               ...                           ...   
106818  RIO GRANDE DO NORTE               GNV                             7   
106819    RIO GRANDE DO SUL               GNV                            23   
106820       SANTA CATARINA               GNV                            24   
106821            SAO PAULO               GNV                            52   
106822              SERGIPE               GNV                             4   

       UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  ...  \
0                   R$/l                1.288                  0.016  ...   
1                   R$/l                1.162                  0.114  ...   
2                   R$/l                1.389                  0.097  ...   
3                   R$/l                1.262                  0.070  ...   
4                   R$/l                1.181                  0.078  ...   
...                  ...                  ...                    ...  ...   
106818             R$/m3                3.574                  0.065  ...   
106819             R$/m3                3.401                  0.129  ...   
106820             R$/m3                2.912                  0.190  ...   
106821             R$/m3                3.020                  0.229  ...   
106822             R$/m3                3.697                  0.005  ...   

        MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                      0.463                     0.012   
1                      0.399                     0.098   
2                      0.419                     0.070   
3                      0.432                     0.055   
4                       0.24                     0.066   
...                      ...                       ...   
106818                 0.818                     0.018   
106819                  0.95                     0.038   
106820                 0.914                     0.065   
106821                 0.646                     0.076   
106822                 1.179                     0.001   

       PREÇO MÉDIO DISTRIBUIÇÃO  DESVIO PADRÃO DISTRIBUIÇÃO  \
0                         0.825                        0.11   
1                         0.763                       0.088   
2                          0.97                       0.095   
3                          0.83                       0.119   
4                         0.941                       0.077   
...                         ...                         ...   
106818                    2.756                           0   
106819                    2.451                       0.402   
106820                    1.998                           0   
106821                    2.374                       0.165   
106822     

In [79]:
data['coluna a partir de lista'] = range(data.shape[0])
data

Unnamed: 0 DATA INICIAL  DATA FINAL        REGIÃO  \
0                0   2004-05-09  2004-05-15  CENTRO OESTE   
1                1   2004-05-09  2004-05-15  CENTRO OESTE   
2                2   2004-05-09  2004-05-15  CENTRO OESTE   
3                3   2004-05-09  2004-05-15  CENTRO OESTE   
4                4   2004-05-09  2004-05-15      NORDESTE   
...            ...          ...         ...           ...   
106818      106818   2019-06-23  2019-06-29      NORDESTE   
106819      106819   2019-06-23  2019-06-29           SUL   
106820      106820   2019-06-23  2019-06-29           SUL   
106821      106821   2019-06-23  2019-06-29       SUDESTE   
106822      106822   2019-06-23  2019-06-29      NORDESTE   

                     ESTADO           PRODUTO  NÚMERO DE POSTOS PESQUISADOS  \
0          DISTRITO FEDERAL  ETANOL HIDRATADO                           127   
1                     GOIAS  ETANOL HIDRATADO                           387   
2               MATO GROSSO  ETANOL HIDRATADO                           192   
3        MATO GROSSO DO SUL  ETANOL HIDRATADO                           162   
4                   ALAGOAS  ETANOL HIDRATADO                           103   
...                     ...               ...                           ...   
106818  RIO GRANDE DO NORTE               GNV                             7   
106819    RIO GRANDE DO SUL               GNV                            23   
106820       SANTA CATARINA               GNV                            24   
106821            SAO PAULO               GNV                            52   
106822              SERGIPE               GNV                             4   

       UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  ...  \
0                   R$/l                1.288                  0.016  ...   
1                   R$/l                1.162                  0.114  ...   
2                   R$/l                1.389                  0.097  ...   
3                   R$/l                1.262                  0.070  ...   
4                   R$/l                1.181                  0.078  ...   
...                  ...                  ...                    ...  ...   
106818             R$/m3                3.574                  0.065  ...   
106819             R$/m3                3.401                  0.129  ...   
106820             R$/m3                2.912                  0.190  ...   
106821             R$/m3                3.020                  0.229  ...   
106822             R$/m3                3.697                  0.005  ...   

        COEF DE VARIAÇÃO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO  \
0                          0.012                     0.825   
1                          0.098                     0.763   
2                          0.070                      0.97   
3                          0.055                      0.83   
4                          0.066                     0.941   
...                          ...                       ...   
106818                     0.018                     2.756   
106819                     0.038                     2.451   
106820                     0.065                     1.998   
106821                     0.076                     2.374   
106822                     0.001                     2.518   

       DESVIO PADRÃO DISTRIBUIÇÃO  PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                            0.11                     0.4201   
1                           0.088                     0.5013   
2                           0.095                     0.5614   
3                           0.119                     0.5991   
4                           0.077                     0.7441   
...                           ...                        ...   
106818                          0                      2.756   
106819                      0.402                     1.9842   
106820                          0                     1.9981   
106821          

In [80]:
# Não funciona pq a quantidade de elementos a lista é diferente a quandidade de linha do data frame.

## data['nao funciona'] = [1, 2, 3]
##data

In [81]:
# Criando uma nova colunado a partir de uma coluna já existente.

data['PREÇO MÉDIO REVENDA (DÓLARES)'] = data['PREÇO MÉDIO REVENDA'] * 6.0
data

Unnamed: 0 DATA INICIAL  DATA FINAL        REGIÃO  \
0                0   2004-05-09  2004-05-15  CENTRO OESTE   
1                1   2004-05-09  2004-05-15  CENTRO OESTE   
2                2   2004-05-09  2004-05-15  CENTRO OESTE   
3                3   2004-05-09  2004-05-15  CENTRO OESTE   
4                4   2004-05-09  2004-05-15      NORDESTE   
...            ...          ...         ...           ...   
106818      106818   2019-06-23  2019-06-29      NORDESTE   
106819      106819   2019-06-23  2019-06-29           SUL   
106820      106820   2019-06-23  2019-06-29           SUL   
106821      106821   2019-06-23  2019-06-29       SUDESTE   
106822      106822   2019-06-23  2019-06-29      NORDESTE   

                     ESTADO           PRODUTO  NÚMERO DE POSTOS PESQUISADOS  \
0          DISTRITO FEDERAL  ETANOL HIDRATADO                           127   
1                     GOIAS  ETANOL HIDRATADO                           387   
2               MATO GROSSO  ETANOL HIDRATADO                           192   
3        MATO GROSSO DO SUL  ETANOL HIDRATADO                           162   
4                   ALAGOAS  ETANOL HIDRATADO                           103   
...                     ...               ...                           ...   
106818  RIO GRANDE DO NORTE               GNV                             7   
106819    RIO GRANDE DO SUL               GNV                            23   
106820       SANTA CATARINA               GNV                            24   
106821            SAO PAULO               GNV                            52   
106822              SERGIPE               GNV                             4   

       UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  ...  \
0                   R$/l                1.288                  0.016  ...   
1                   R$/l                1.162                  0.114  ...   
2                   R$/l                1.389                  0.097  ...   
3                   R$/l                1.262                  0.070  ...   
4                   R$/l                1.181                  0.078  ...   
...                  ...                  ...                    ...  ...   
106818             R$/m3                3.574                  0.065  ...   
106819             R$/m3                3.401                  0.129  ...   
106820             R$/m3                2.912                  0.190  ...   
106821             R$/m3                3.020                  0.229  ...   
106822             R$/m3                3.697                  0.005  ...   

        PREÇO MÉDIO DISTRIBUIÇÃO  DESVIO PADRÃO DISTRIBUIÇÃO  \
0                          0.825                        0.11   
1                          0.763                       0.088   
2                           0.97                       0.095   
3                           0.83                       0.119   
4                          0.941                       0.077   
...                          ...                         ...   
106818                     2.756                           0   
106819                     2.451                       0.402   
106820                     1.998                           0   
106821                     2.374                       0.165   
106822                     2.518                           0   

       PREÇO MÍNIMO DISTRIBUIÇÃO  PREÇO MÁXIMO DISTRIBUIÇÃO  \
0                         0.4201                     0.9666   
1                         0.5013                       1.05   
2                         0.5614                      1.161   
3                         0.5991                    1.22242   
4                         0.7441                     1.0317   
...                          ...                        ...   
106818                     2.756                      2.756   
106819                    1.9842                     2.8661   
106820                    1.9981                     1.9981   
10

##### 1.3.4 Índices

Todo Data Frame possui **índices**, que não são considerados colunas da tabela. Tais índices são comumente **númericos**, de 0 a num_linhas-1, mas também podem ser **textuais(rótulos/labels)**.

In [82]:
data.index

RangeIndex(start=0, stop=106823, step=1)

- **Exemplo de Data Frame com índices Textuais(Labels)**

In [83]:
pesquisa_de_satisfacao = pd.DataFrame({
    'bom': [50, 100, 200],
    'ruim': [400, 600, 1000],
    'pessimo': [0, 1 ,3]
}, index=['XboxOne', 'Playstation5', 'Switch'])
pesquisa_de_satisfacao.head()

bom  ruim  pessimo
XboxOne        50   400        0
Playstation5  100   600        1
Switch        200  1000        3

In [84]:
pesquisa_de_satisfacao.index

Index(['XboxOne', 'Playstation5', 'Switch'], dtype='object')

- Idex-based selection (Seleção baseada em índices)

monstrando linhas específicas de um DataFrame:

`ilorc`: seleciona elementos do DataFrame, baeado em seu **índice(número)** --> row-first, column-second


**Selecionando uma observação/linha**

In [85]:
data.iloc[1]

Unnamed: 0                                      1
DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
MÊS                                             5


**Selecionando múltiplas observações/linhas:**

In [86]:
data.iloc[:7]

Unnamed: 0 DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0           0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1           1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2           2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3           3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4           4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   
5           5   2004-05-09  2004-05-15      NORDESTE               BAHIA   
6           6   2004-05-09  2004-05-15      NORDESTE               CEARA   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   
5  ETANOL HIDRATADO                           408              R$/l   
6  ETANOL HIDRATADO                           278              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  ...  PREÇO MÉDIO DISTRIBUIÇÃO  \
0                1.288                  0.016  ...                     0.825   
1                1.162                  0.114  ...                     0.763   
2                1.389                  0.097  ...                      0.97   
3                1.262                  0.070  ...                      0.83   
4                1.181                  0.078  ...                     0.941   
5                1.383                  0.132  ...                     0.957   
6                1.453                  0.218  ...                       1.1   

   DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                        0.11                    0.4201   
1                       0.088                    0.5013   
2                       0.095                    0.5614   
3                       0.119                    0.5991   
4                       0.077                    0.7441   
5                       0.128                    0.5686   
6                       0.068                    0.7332   

   PREÇO MÁXIMO DISTRIBUIÇÃO COEF DE VARIAÇÃO DISTRIBUIÇÃO MÊS   ANO  \
0                     0.9666                         0.133   5  2004   
1                       1.05                         0.115   5  2004   
2                      1.161                         0.098   5  2004   
3                    1.22242                         0.143   5  2004   
4                     1.0317                         0.082   5  2004   
5                       1.35                         0.134   5  2004   
6                      1.294                         0.062   5  2004   

  colunar sem nocao coluna a partir de lista  PREÇO MÉDIO REVENDA (DÓLARES)  
0           DEFAULT                        0                          7.728  
1           DEFAULT                        1                          6.972  
2           DEFAULT                        2                          8.334  
3           DEFAULT                        3                          7.572  
4           DEFAULT                        4                          7.086  
5           DEFAULT                        5                          8.298  
6           DEFAULT                        6                          8.718  

[7 rows x 24 columns]

In [87]:
data.iloc[10:25]

Unnamed: 0 DATA INICIAL  DATA FINAL    REGIÃO               ESTADO  \
10          10   2004-05-09  2004-05-15  NORDESTE                PIAUI   
11          11   2004-05-09  2004-05-15  NORDESTE  RIO GRANDE DO NORTE   
12          12   2004-05-09  2004-05-15  NORDESTE              SERGIPE   
13          13   2004-05-09  2004-05-15     NORTE                 ACRE   
14          14   2004-05-09  2004-05-15     NORTE                AMAPA   
15          15   2004-05-09  2004-05-15     NORTE             AMAZONAS   
16          16   2004-05-09  2004-05-15     NORTE                 PARA   
17          17   2004-05-09  2004-05-15     NORTE             RONDONIA   
18          18   2004-05-09  2004-05-15     NORTE              RORAIMA   
19          19   2004-05-09  2004-05-15     NORTE            TOCANTINS   
20          20   2004-05-09  2004-05-15   SUDESTE       ESPIRITO SANTO   
21          21   2004-05-09  2004-05-15   SUDESTE         MINAS GERAIS   
22          22   2004-05-09  2004-05-15   SUDESTE       RIO DE JANEIRO   
23          23   2004-05-09  2004-05-15   SUDESTE            SAO PAULO   
24          24   2004-05-09  2004-05-15       SUL               PARANA   

             PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
10  ETANOL HIDRATADO                            89              R$/l   
11  ETANOL HIDRATADO                           131              R$/l   
12  ETANOL HIDRATADO                            57              R$/l   
13  ETANOL HIDRATADO                            33              R$/l   
14  ETANOL HIDRATADO                            15              R$/l   
15  ETANOL HIDRATADO                            53              R$/l   
16  ETANOL HIDRATADO                           104              R$/l   
17  ETANOL HIDRATADO                            97              R$/l   
18  ETANOL HIDRATADO                            14              R$/l   
19  ETANOL HIDRATADO                            71              R$/l   
20  ETANOL HIDRATADO                           306              R$/l   
21  ETANOL HIDRATADO                          1238              R$/l   
22  ETANOL HIDRATADO                           952              R$/l   
23  ETANOL HIDRATADO                          4047              R$/l   
24  ETANOL HIDRATADO                           760              R$/l   

    PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  ...  PREÇO MÉDIO DISTRIBUIÇÃO  \
10                1.573                  0.134  ...                     1.079   
11                1.276                  0.116  ...                     0.944   
12                1.301                  0.109  ...                      0.98   
13                1.805                  0.134  ...                     1.116   
14                1.785                  0.035  ...                     1.373   
15                1.578                  0.123  ...                     1.137   
16                1.914                  0.246  ...                     1.378   
17                1.545                  0.141  ...                     1.012   
18                1.300                  0.000  ...                     1.098   
19                1.226                  0.081  ...                      0.68   
20                1.148                  0.116  ...                     0.881   
21                1.205                  0.120  ...                     0.816   
22                1.098                  0.154  ...                     0.786   
23                0.768                  0.085  ...                      0.57   
24                0.922                  0.083  ...                     0.667   

    DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
10                       0.078                    0.8857   
11                       0.078                    0.7119   
12                       0.052                    0.8267   
13                       0.171                     0.767   
14                       0.167                    0.8339   
15       

In [88]:
data.iloc[[1,2,6,7,8]]

Unnamed: 0 DATA INICIAL  DATA FINAL        REGIÃO       ESTADO  \
1           1   2004-05-09  2004-05-15  CENTRO OESTE        GOIAS   
2           2   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO   
6           6   2004-05-09  2004-05-15      NORDESTE        CEARA   
7           7   2004-05-09  2004-05-15      NORDESTE     MARANHAO   
8           8   2004-05-09  2004-05-15      NORDESTE      PARAIBA   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
6  ETANOL HIDRATADO                           278              R$/l   
7  ETANOL HIDRATADO                           105              R$/l   
8  ETANOL HIDRATADO                           125              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  ...  PREÇO MÉDIO DISTRIBUIÇÃO  \
1                1.162                  0.114  ...                     0.763   
2                1.389                  0.097  ...                      0.97   
6                1.453                  0.218  ...                       1.1   
7                1.631                  0.158  ...                     1.116   
8                1.284                  0.130  ...                     0.931   

   DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
1                       0.088                    0.5013   
2                       0.095                    0.5614   
6                       0.068                    0.7332   
7                       0.091                    0.9923   
8                       0.072                    0.7577   

   PREÇO MÁXIMO DISTRIBUIÇÃO COEF DE VARIAÇÃO DISTRIBUIÇÃO MÊS   ANO  \
1                       1.05                         0.115   5  2004   
2                      1.161                         0.098   5  2004   
6                      1.294                         0.062   5  2004   
7                    1.36183                         0.082   5  2004   
8                     1.2972                         0.077   5  2004   

  colunar sem nocao coluna a partir de lista  PREÇO MÉDIO REVENDA (DÓLARES)  
1           DEFAULT                        1                          6.972  
2           DEFAULT                        2                          8.334  
6           DEFAULT                        6                          8.718  
7           DEFAULT                        7                          9.786  
8           DEFAULT                        8                          7.704  

[5 rows x 24 columns]

In [89]:
data.iloc[1, 4] # Linha 1 Coluna 3

'GOIAS'

- Label-based selection (Seleção baseadas em Rótulos)

`loc`: seleciona elementos do DataFrame, baseado em seus **rótulos** -> row-first, column-second

In [90]:
# Retorna a linha cujo o tótulo do índice é 'XboxOne'
pesquisa_de_satisfacao.loc['XboxOne']

bom         50
ruim       400
pessimo      0
Name: XboxOne, dtype: int64

In [91]:
# retorna o valor da linha 'XboxOne' e coluna 'ruim'
pesquisa_de_satisfacao.loc['XboxOne', 'ruim']

400

In [92]:
# retorna o valor das linhas 'XboxOne' e 'Switch'
pesquisa_de_satisfacao.loc[['XboxOne', 'Switch']]

bom  ruim  pessimo
XboxOne   50   400        0
Switch   200  1000        3

In [93]:
# retorna todas as linhas e apenas as colunas com rótulos 'bom'e 'péssimo'

pesquisa_de_satisfacao[['bom', 'pessimo']]

bom  pessimo
XboxOne        50        0
Playstation5  100        1
Switch        200        3

In [94]:
# retorna todas as linhas e apenas as colunas com rótulos 'bom'e 'péssimo'
pesquisa_de_satisfacao.loc[:,['bom', 'pessimo']]

bom  pessimo
XboxOne        50        0
Playstation5  100        1
Switch        200        3

In [95]:
data

Unnamed: 0 DATA INICIAL  DATA FINAL        REGIÃO  \
0                0   2004-05-09  2004-05-15  CENTRO OESTE   
1                1   2004-05-09  2004-05-15  CENTRO OESTE   
2                2   2004-05-09  2004-05-15  CENTRO OESTE   
3                3   2004-05-09  2004-05-15  CENTRO OESTE   
4                4   2004-05-09  2004-05-15      NORDESTE   
...            ...          ...         ...           ...   
106818      106818   2019-06-23  2019-06-29      NORDESTE   
106819      106819   2019-06-23  2019-06-29           SUL   
106820      106820   2019-06-23  2019-06-29           SUL   
106821      106821   2019-06-23  2019-06-29       SUDESTE   
106822      106822   2019-06-23  2019-06-29      NORDESTE   

                     ESTADO           PRODUTO  NÚMERO DE POSTOS PESQUISADOS  \
0          DISTRITO FEDERAL  ETANOL HIDRATADO                           127   
1                     GOIAS  ETANOL HIDRATADO                           387   
2               MATO GROSSO  ETANOL HIDRATADO                           192   
3        MATO GROSSO DO SUL  ETANOL HIDRATADO                           162   
4                   ALAGOAS  ETANOL HIDRATADO                           103   
...                     ...               ...                           ...   
106818  RIO GRANDE DO NORTE               GNV                             7   
106819    RIO GRANDE DO SUL               GNV                            23   
106820       SANTA CATARINA               GNV                            24   
106821            SAO PAULO               GNV                            52   
106822              SERGIPE               GNV                             4   

       UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  ...  \
0                   R$/l                1.288                  0.016  ...   
1                   R$/l                1.162                  0.114  ...   
2                   R$/l                1.389                  0.097  ...   
3                   R$/l                1.262                  0.070  ...   
4                   R$/l                1.181                  0.078  ...   
...                  ...                  ...                    ...  ...   
106818             R$/m3                3.574                  0.065  ...   
106819             R$/m3                3.401                  0.129  ...   
106820             R$/m3                2.912                  0.190  ...   
106821             R$/m3                3.020                  0.229  ...   
106822             R$/m3                3.697                  0.005  ...   

        PREÇO MÉDIO DISTRIBUIÇÃO  DESVIO PADRÃO DISTRIBUIÇÃO  \
0                          0.825                        0.11   
1                          0.763                       0.088   
2                           0.97                       0.095   
3                           0.83                       0.119   
4                          0.941                       0.077   
...                          ...                         ...   
106818                     2.756                           0   
106819                     2.451                       0.402   
106820                     1.998                           0   
106821                     2.374                       0.165   
106822                     2.518                           0   

       PREÇO MÍNIMO DISTRIBUIÇÃO  PREÇO MÁXIMO DISTRIBUIÇÃO  \
0                         0.4201                     0.9666   
1                         0.5013                       1.05   
2                         0.5614                      1.161   
3                         0.5991                    1.22242   
4                         0.7441                     1.0317   
...                          ...                        ...   
106818                     2.756                      2.756   
106819                    1.9842                     2.8661   
106820                    1.9981                     1.9981   
10

In [96]:
data.loc[10:15,['ESTADO', 'PREÇO MÉDIO REVENDA']]

ESTADO  PREÇO MÉDIO REVENDA
10                PIAUI                1.573
11  RIO GRANDE DO NORTE                1.276
12              SERGIPE                1.301
13                 ACRE                1.805
14                AMAPA                1.785
15             AMAZONAS                1.578

#### 1.4 Removendo um Atributo (Coluna) do Data Frame

In [97]:
data.head()

Unnamed: 0 DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0           0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1           1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2           2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3           3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4           4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  ...  PREÇO MÉDIO DISTRIBUIÇÃO  \
0                1.288                  0.016  ...                     0.825   
1                1.162                  0.114  ...                     0.763   
2                1.389                  0.097  ...                      0.97   
3                1.262                  0.070  ...                      0.83   
4                1.181                  0.078  ...                     0.941   

   DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                        0.11                    0.4201   
1                       0.088                    0.5013   
2                       0.095                    0.5614   
3                       0.119                    0.5991   
4                       0.077                    0.7441   

   PREÇO MÁXIMO DISTRIBUIÇÃO COEF DE VARIAÇÃO DISTRIBUIÇÃO MÊS   ANO  \
0                     0.9666                         0.133   5  2004   
1                       1.05                         0.115   5  2004   
2                      1.161                         0.098   5  2004   
3                    1.22242                         0.143   5  2004   
4                     1.0317                         0.082   5  2004   

  colunar sem nocao coluna a partir de lista  PREÇO MÉDIO REVENDA (DÓLARES)  
0           DEFAULT                        0                          7.728  
1           DEFAULT                        1                          6.972  
2           DEFAULT                        2                          8.334  
3           DEFAULT                        3                          7.572  
4           DEFAULT                        4                          7.086  

[5 rows x 24 columns]

In [98]:
# DELETA/REMOVE in-place(ou seja, no próprio dataframe) a colunar de rótulo 'Unnamed: 0'.
del data['Unnamed: 0']

In [99]:
# Removendo as colunas criadas para testes.

del data['coluna a partir de lista']
del data['PREÇO MÉDIO REVENDA (DÓLARES)']
del data['colunar sem nocao']

data.head(4)

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                1.288                  0.016                  1.19   
1                1.162                  0.114                  0.89   
2                1.389                  0.097                  1.18   
3                1.262                  0.070                  1.09   

   PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                 1.350                0.463                     0.012   
1                 1.449                0.399                     0.098   
2                 1.760                0.419                     0.070   
3                 1.509                0.432                     0.055   

  PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                    0.825                       0.11   
1                    0.763                      0.088   
2                     0.97                      0.095   
3                     0.83                      0.119   

  PREÇO MÍNIMO DISTRIBUIÇÃO PREÇO MÁXIMO DISTRIBUIÇÃO  \
0                    0.4201                    0.9666   
1                    0.5013                      1.05   
2                    0.5614                     1.161   
3                    0.5991                   1.22242   

  COEF DE VARIAÇÃO DISTRIBUIÇÃO  MÊS   ANO  
0                         0.133    5  2004  
1                         0.115    5  2004  
2                         0.098    5  2004  
3                         0.143    5  2004

#### 1.5 Salvando um Data Frame

Para salvarmos um Data Frame para um arquivos CSV, basta usar o método `.to csv`</br>
Por padrão, esse método **salva os índices da tabela como uma coluna CSV**</br>
Como no geral tais índices são números de 0 a n-1, não há necessidade para isso (veja que removemos anteriormente a coluna 'Unnamed: 0'que foi justamente esse caso).</br>
Desta forma, utilize o parâmetro: `index=False`.

Por padrão, o método utilizará a ',' como separador das colunas. Caso queira alterá-lo, utilize o parâmetro `sep`.

In [100]:
data.to_csv('./datasets/Preco_Combustiveis_preprocessado.csv', index=False)

#### 1.6 Seleção Condicional: Filtrando amostras

Durante nossas análises exploratórias, frequentemente filtraremos nossas amostras, a partir de certas **codiçòes**, para fins de análise mais específicas.</br>
Existem algumas maneiras de fazermos tal filtragem. Antes disso, vamos carregar nosso dataset pré-processado que salvamos no item anterior.

In [101]:
data = pd.read_csv('./datasets/Preco_Combustiveis_preprocessado.csv')

In [102]:
data.head()

DATA INICIAL  DATA FINAL        REGIÃO              ESTADO  \
0   2004-05-09  2004-05-15  CENTRO OESTE    DISTRITO FEDERAL   
1   2004-05-09  2004-05-15  CENTRO OESTE               GOIAS   
2   2004-05-09  2004-05-15  CENTRO OESTE         MATO GROSSO   
3   2004-05-09  2004-05-15  CENTRO OESTE  MATO GROSSO DO SUL   
4   2004-05-09  2004-05-15      NORDESTE             ALAGOAS   

            PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0  ETANOL HIDRATADO                           127              R$/l   
1  ETANOL HIDRATADO                           387              R$/l   
2  ETANOL HIDRATADO                           192              R$/l   
3  ETANOL HIDRATADO                           162              R$/l   
4  ETANOL HIDRATADO                           103              R$/l   

   PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                1.288                  0.016                  1.19   
1                1.162                  0.114                  0.89   
2                1.389                  0.097                  1.18   
3                1.262                  0.070                  1.09   
4                1.181                  0.078                  1.05   

   PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                 1.350                0.463                     0.012   
1                 1.449                0.399                     0.098   
2                 1.760                0.419                     0.070   
3                 1.509                0.432                     0.055   
4                 1.400                 0.24                     0.066   

  PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                    0.825                       0.11   
1                    0.763                      0.088   
2                     0.97                      0.095   
3                     0.83                      0.119   
4                    0.941                      0.077   

  PREÇO MÍNIMO DISTRIBUIÇÃO PREÇO MÁXIMO DISTRIBUIÇÃO  \
0                    0.4201                    0.9666   
1                    0.5013                      1.05   
2                    0.5614                     1.161   
3                    0.5991                   1.22242   
4                    0.7441                    1.0317   

  COEF DE VARIAÇÃO DISTRIBUIÇÃO  MÊS   ANO  
0                         0.133    5  2004  
1                         0.115    5  2004  
2                         0.098    5  2004  
3                         0.143    5  2004  
4                         0.082    5  2004

In [103]:
# retornar um array com os valores únicos contidos na coluna ESTADO

data['ESTADO'].unique() 

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

- Selecionando apenas os preços dos Postos de SÃO PAULO.

**Alternativa 1: Selecção Condicional (Comparações diretas)**</br>
O código abaixo retorna uma **Series(array) de booleans**, como o número de linhas(observações) do DF, que informa os registros de preço dos postos do _estado de SÃO PAULO (True)_

In [104]:
# Faz uma comparação de elemento a elemento da Series, retornando uma Series de boobleans
data['ESTADO'] == 'SAO PAULO'

0         False
1         False
2         False
3         False
4         False
          ...  
106818    False
106819    False
106820    False
106821     True
106822    False
Name: ESTADO, Length: 106823, dtype: bool

In [105]:
#salvando a Series de booleans em uma variável
selecao = data['ESTADO'] == 'SAO PAULO'

Para **filtrarmos** os registros de postos do estado de São Paulo:

In [106]:
data[selecao]

DATA INICIAL  DATA FINAL   REGIÃO     ESTADO           PRODUTO  \
23       2004-05-09  2004-05-15  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
50       2004-05-16  2004-05-22  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
77       2004-05-23  2004-05-29  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
104      2004-05-30  2004-06-05  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
131      2004-06-06  2004-06-12  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
...             ...         ...      ...        ...               ...   
106724   2019-06-23  2019-06-29  SUDESTE  SAO PAULO       ÓLEO DIESEL   
106751   2019-06-23  2019-06-29  SUDESTE  SAO PAULO   ÓLEO DIESEL S10   
106778   2019-06-23  2019-06-29  SUDESTE  SAO PAULO    GASOLINA COMUM   
106805   2019-06-23  2019-06-29  SUDESTE  SAO PAULO               GLP   
106821   2019-06-23  2019-06-29  SUDESTE  SAO PAULO               GNV   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
23                              4047              R$/l                0.768   
50                              4066              R$/l                0.766   
77                              4077              R$/l                0.823   
104                             4073              R$/l                0.887   
131                             4082              R$/l                0.894   
...                              ...               ...                  ...   
106724                           863              R$/l                3.448   
106751                          1277              R$/l                3.574   
106778                          1644              R$/l                4.142   
106805                          1017           R$/13Kg               66.893   
106821                            52             R$/m3                3.020   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
23                      0.085                 0.590                 1.150   
50                      0.083                 0.590                 1.150   
77                      0.071                 0.620                 1.199   
104                     0.075                 0.639                 1.359   
131                     0.071                 0.669                 1.199   
...                       ...                   ...                   ...   
106724                  0.156                 3.099                 4.220   
106751                  0.169                 3.199                 4.320   
106778                  0.183                 3.769                 4.999   
106805                  6.100                50.000                89.900   
106821                  0.229                 2.699                 3.490   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
23                    0.198                     0.111   
50                     0.19                     0.108   
77                    0.209                     0.086   
104                   0.216                     0.085   
131                   0.205                     0.079   
...                     ...                       ...   
106724                0.401                     0.045   
106751                0.451                     0.047   
106778                0.429                     0.044   
106805               17.679                     0.091   
106821                0.646                     0.076   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
23                         0.57                      0.056   
50                        0.576                       0.05   
77                        0.614                      0.063   
104                       0.671                      0.075   
131                       0.689                      0.072   
...                         ...                        ...   
106724                    3.047                      0.097   
106751                    3.123                      0.111   
106778       

O resultado é um DF com apenas os registros desejados após a **filtragem**.</br>
Podemos ainda utilizar o método `loc` para o mesmo fim:

In [107]:
data.loc[selecao]

DATA INICIAL  DATA FINAL   REGIÃO     ESTADO           PRODUTO  \
23       2004-05-09  2004-05-15  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
50       2004-05-16  2004-05-22  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
77       2004-05-23  2004-05-29  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
104      2004-05-30  2004-06-05  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
131      2004-06-06  2004-06-12  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
...             ...         ...      ...        ...               ...   
106724   2019-06-23  2019-06-29  SUDESTE  SAO PAULO       ÓLEO DIESEL   
106751   2019-06-23  2019-06-29  SUDESTE  SAO PAULO   ÓLEO DIESEL S10   
106778   2019-06-23  2019-06-29  SUDESTE  SAO PAULO    GASOLINA COMUM   
106805   2019-06-23  2019-06-29  SUDESTE  SAO PAULO               GLP   
106821   2019-06-23  2019-06-29  SUDESTE  SAO PAULO               GNV   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
23                              4047              R$/l                0.768   
50                              4066              R$/l                0.766   
77                              4077              R$/l                0.823   
104                             4073              R$/l                0.887   
131                             4082              R$/l                0.894   
...                              ...               ...                  ...   
106724                           863              R$/l                3.448   
106751                          1277              R$/l                3.574   
106778                          1644              R$/l                4.142   
106805                          1017           R$/13Kg               66.893   
106821                            52             R$/m3                3.020   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
23                      0.085                 0.590                 1.150   
50                      0.083                 0.590                 1.150   
77                      0.071                 0.620                 1.199   
104                     0.075                 0.639                 1.359   
131                     0.071                 0.669                 1.199   
...                       ...                   ...                   ...   
106724                  0.156                 3.099                 4.220   
106751                  0.169                 3.199                 4.320   
106778                  0.183                 3.769                 4.999   
106805                  6.100                50.000                89.900   
106821                  0.229                 2.699                 3.490   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
23                    0.198                     0.111   
50                     0.19                     0.108   
77                    0.209                     0.086   
104                   0.216                     0.085   
131                   0.205                     0.079   
...                     ...                       ...   
106724                0.401                     0.045   
106751                0.451                     0.047   
106778                0.429                     0.044   
106805               17.679                     0.091   
106821                0.646                     0.076   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
23                         0.57                      0.056   
50                        0.576                       0.05   
77                        0.614                      0.063   
104                       0.671                      0.075   
131                       0.689                      0.072   
...                         ...                        ...   
106724                    3.047                      0.097   
106751                    3.123                      0.111   
106778       

** Alternativa 2: Utilizando o método `query`**

`query` filtra linhas de um DF baseado em uma **query(pergunta)**.


In [108]:
data.query('ESTADO == "PERNAMBUCO"')

DATA INICIAL  DATA FINAL    REGIÃO      ESTADO           PRODUTO  \
9        2004-05-09  2004-05-15  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
36       2004-05-16  2004-05-22  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
63       2004-05-23  2004-05-29  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
90       2004-05-30  2004-06-05  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
117      2004-06-06  2004-06-12  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
...             ...         ...       ...         ...               ...   
106716   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO       ÓLEO DIESEL   
106743   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO   ÓLEO DIESEL S10   
106770   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO    GASOLINA COMUM   
106797   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO               GLP   
106816   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO               GNV   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
9                                423              R$/l                1.224   
36                               435              R$/l                1.217   
63                               421              R$/l                1.217   
90                               425              R$/l                1.216   
117                              415              R$/l                1.235   
...                              ...               ...                  ...   
106716                             8              R$/l                3.681   
106743                           174              R$/l                3.556   
106770                           192              R$/l                4.445   
106797                           165           R$/13Kg               66.735   
106816                            12             R$/m3                2.698   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
9                       0.141                 0.989                 1.700   
36                      0.137                 0.990                 1.700   
63                      0.136                 0.989                 1.700   
90                      0.131                 0.989                 1.700   
117                     0.119                 0.990                 1.700   
...                       ...                   ...                   ...   
106716                  0.132                 3.429                 3.819   
106743                  0.143                 3.299                 4.340   
106770                  0.187                 4.190                 4.999   
106797                  3.701                54.000                80.000   
106816                  0.260                 2.690                 3.600   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
9                     0.277                     0.115   
36                    0.286                     0.113   
63                    0.271                     0.112   
90                    0.253                     0.108   
117                   0.263                     0.096   
...                     ...                       ...   
106716                0.405                     0.036   
106743                 0.45                     0.040   
106770                  0.5                     0.042   
106797               13.237                     0.055   
106816                0.791                     0.096   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
9                         0.947                      0.091   
36                        0.931                      0.078   
63                        0.946                      0.079   
90                        0.963                      0.075   
117                       0.972                      0.084   
...                         ...                        ...   
106716                    3.276                      0.125   
106743                    3.106                    

</br>

Uma boa prática é **salvar o DF filtrado em uma nova variável**. Isso simplifica a complexidade do código para futuras análises feitas para os postos de São Paulo.

In [109]:
postos_pe = data.query('ESTADO == "PERNAMBUCO"')

In [110]:
postos_pe

DATA INICIAL  DATA FINAL    REGIÃO      ESTADO           PRODUTO  \
9        2004-05-09  2004-05-15  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
36       2004-05-16  2004-05-22  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
63       2004-05-23  2004-05-29  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
90       2004-05-30  2004-06-05  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
117      2004-06-06  2004-06-12  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
...             ...         ...       ...         ...               ...   
106716   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO       ÓLEO DIESEL   
106743   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO   ÓLEO DIESEL S10   
106770   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO    GASOLINA COMUM   
106797   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO               GLP   
106816   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO               GNV   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
9                                423              R$/l                1.224   
36                               435              R$/l                1.217   
63                               421              R$/l                1.217   
90                               425              R$/l                1.216   
117                              415              R$/l                1.235   
...                              ...               ...                  ...   
106716                             8              R$/l                3.681   
106743                           174              R$/l                3.556   
106770                           192              R$/l                4.445   
106797                           165           R$/13Kg               66.735   
106816                            12             R$/m3                2.698   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
9                       0.141                 0.989                 1.700   
36                      0.137                 0.990                 1.700   
63                      0.136                 0.989                 1.700   
90                      0.131                 0.989                 1.700   
117                     0.119                 0.990                 1.700   
...                       ...                   ...                   ...   
106716                  0.132                 3.429                 3.819   
106743                  0.143                 3.299                 4.340   
106770                  0.187                 4.190                 4.999   
106797                  3.701                54.000                80.000   
106816                  0.260                 2.690                 3.600   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
9                     0.277                     0.115   
36                    0.286                     0.113   
63                    0.271                     0.112   
90                    0.253                     0.108   
117                   0.263                     0.096   
...                     ...                       ...   
106716                0.405                     0.036   
106743                 0.45                     0.040   
106770                  0.5                     0.042   
106797               13.237                     0.055   
106816                0.791                     0.096   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
9                         0.947                      0.091   
36                        0.931                      0.078   
63                        0.946                      0.079   
90                        0.963                      0.075   
117                       0.972                      0.084   
...                         ...                        ...   
106716                    3.276                      0.125   
106743                    3.106                    

In [111]:
type(postos_pe)

pandas.core.frame.DataFrame

In [112]:
postos_pe.shape

(4262, 20)

In [113]:
postos_pe.head()

DATA INICIAL  DATA FINAL    REGIÃO      ESTADO           PRODUTO  \
9     2004-05-09  2004-05-15  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
36    2004-05-16  2004-05-22  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
63    2004-05-23  2004-05-29  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
90    2004-05-30  2004-06-05  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
117   2004-06-06  2004-06-12  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   

     NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
9                             423              R$/l                1.224   
36                            435              R$/l                1.217   
63                            421              R$/l                1.217   
90                            425              R$/l                1.216   
117                           415              R$/l                1.235   

     DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
9                    0.141                 0.989                   1.7   
36                   0.137                 0.990                   1.7   
63                   0.136                 0.989                   1.7   
90                   0.131                 0.989                   1.7   
117                  0.119                 0.990                   1.7   

    MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA PREÇO MÉDIO DISTRIBUIÇÃO  \
9                  0.277                     0.115                    0.947   
36                 0.286                     0.113                    0.931   
63                 0.271                     0.112                    0.946   
90                 0.253                     0.108                    0.963   
117                0.263                     0.096                    0.972   

    DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
9                        0.091                    0.5643   
36                       0.078                     0.682   
63                       0.079                     0.682   
90                       0.075                     0.682   
117                      0.084                     0.682   

    PREÇO MÁXIMO DISTRIBUIÇÃO COEF DE VARIAÇÃO DISTRIBUIÇÃO  MÊS   ANO  
9                      1.3541                         0.096    5  2004  
36                     1.2666                         0.084    5  2004  
63                     1.2666                         0.084    5  2004  
90                     1.2971                         0.078    5  2004  
117                    1.2971                         0.086    6  2004

- Resetando os índices

Note que os índices das linhas/registros após a filtragem **continuam sendo os mesmo** do DF original.</br>
Em muitas situações, manter esta configuração será importante.</br></br>
Mas, se você quiser **resetar os índices** do DF filtrado, fazendo com que os registros começem com índice 0 até n-1, use o método `.reset_index`.

In [114]:
postos_pe.reset_index()

index DATA INICIAL  DATA FINAL    REGIÃO      ESTADO           PRODUTO  \
0          9   2004-05-09  2004-05-15  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
1         36   2004-05-16  2004-05-22  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
2         63   2004-05-23  2004-05-29  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
3         90   2004-05-30  2004-06-05  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
4        117   2004-06-06  2004-06-12  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
...      ...          ...         ...       ...         ...               ...   
4257  106716   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO       ÓLEO DIESEL   
4258  106743   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO   ÓLEO DIESEL S10   
4259  106770   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO    GASOLINA COMUM   
4260  106797   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO               GLP   
4261  106816   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO               GNV   

      NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
0                              423              R$/l                1.224   
1                              435              R$/l                1.217   
2                              421              R$/l                1.217   
3                              425              R$/l                1.216   
4                              415              R$/l                1.235   
...                            ...               ...                  ...   
4257                             8              R$/l                3.681   
4258                           174              R$/l                3.556   
4259                           192              R$/l                4.445   
4260                           165           R$/13Kg               66.735   
4261                            12             R$/m3                2.698   

      DESVIO PADRÃO REVENDA  ...  PREÇO MÁXIMO REVENDA  MARGEM MÉDIA REVENDA  \
0                     0.141  ...                 1.700                 0.277   
1                     0.137  ...                 1.700                 0.286   
2                     0.136  ...                 1.700                 0.271   
3                     0.131  ...                 1.700                 0.253   
4                     0.119  ...                 1.700                 0.263   
...                     ...  ...                   ...                   ...   
4257                  0.132  ...                 3.819                 0.405   
4258                  0.143  ...                 4.340                  0.45   
4259                  0.187  ...                 4.999                   0.5   
4260                  3.701  ...                80.000                13.237   
4261                  0.260  ...                 3.600                 0.791   

     COEF DE VARIAÇÃO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO  \
0                       0.115                     0.947   
1                       0.113                     0.931   
2                       0.112                     0.946   
3                       0.108                     0.963   
4                       0.096                     0.972   
...                       ...                       ...   
4257                    0.036                     3.276   
4258                    0.040                     3.106   
4259                    0.042                     3.945   
4260                    0.055                    53.498   
4261                    0.096                     1.907   

     DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                         0.091                    0.5643   
1                         0.078                     0.682   
2                         0.079                     0.682   
3                         0.075                     0.682   
4                         0.084                     0.682   
...                         ...                       ...   
4257        

In [115]:
postos_pe.reset_index(drop=True, inplace=True)

In [116]:
postos_pe

DATA INICIAL  DATA FINAL    REGIÃO      ESTADO           PRODUTO  \
0      2004-05-09  2004-05-15  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
1      2004-05-16  2004-05-22  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
2      2004-05-23  2004-05-29  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
3      2004-05-30  2004-06-05  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
4      2004-06-06  2004-06-12  NORDESTE  PERNAMBUCO  ETANOL HIDRATADO   
...           ...         ...       ...         ...               ...   
4257   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO       ÓLEO DIESEL   
4258   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO   ÓLEO DIESEL S10   
4259   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO    GASOLINA COMUM   
4260   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO               GLP   
4261   2019-06-23  2019-06-29  NORDESTE  PERNAMBUCO               GNV   

      NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
0                              423              R$/l                1.224   
1                              435              R$/l                1.217   
2                              421              R$/l                1.217   
3                              425              R$/l                1.216   
4                              415              R$/l                1.235   
...                            ...               ...                  ...   
4257                             8              R$/l                3.681   
4258                           174              R$/l                3.556   
4259                           192              R$/l                4.445   
4260                           165           R$/13Kg               66.735   
4261                            12             R$/m3                2.698   

      DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
0                     0.141                 0.989                 1.700   
1                     0.137                 0.990                 1.700   
2                     0.136                 0.989                 1.700   
3                     0.131                 0.989                 1.700   
4                     0.119                 0.990                 1.700   
...                     ...                   ...                   ...   
4257                  0.132                 3.429                 3.819   
4258                  0.143                 3.299                 4.340   
4259                  0.187                 4.190                 4.999   
4260                  3.701                54.000                80.000   
4261                  0.260                 2.690                 3.600   

     MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA PREÇO MÉDIO DISTRIBUIÇÃO  \
0                   0.277                     0.115                    0.947   
1                   0.286                     0.113                    0.931   
2                   0.271                     0.112                    0.946   
3                   0.253                     0.108                    0.963   
4                   0.263                     0.096                    0.972   
...                   ...                       ...                      ...   
4257                0.405                     0.036                    3.276   
4258                 0.45                     0.040                    3.106   
4259                  0.5                     0.042                    3.945   
4260               13.237                     0.055                   53.498   
4261                0.791                     0.096                    1.907   

     DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                         0.091                    0.5643   
1                         0.078                     0.682   
2                         0.079                     0.682   
3                         0.075                     0.682   
4                         0.084     

- Outra forma 

In [117]:
postos_sp = data.query('ESTADO == "SAO PAULO"').reset_index(drop=True)

In [118]:
postos_sp

DATA INICIAL  DATA FINAL   REGIÃO     ESTADO           PRODUTO  \
0      2004-05-09  2004-05-15  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
1      2004-05-16  2004-05-22  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
2      2004-05-23  2004-05-29  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
3      2004-05-30  2004-06-05  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
4      2004-06-06  2004-06-12  SUDESTE  SAO PAULO  ETANOL HIDRATADO   
...           ...         ...      ...        ...               ...   
4258   2019-06-23  2019-06-29  SUDESTE  SAO PAULO       ÓLEO DIESEL   
4259   2019-06-23  2019-06-29  SUDESTE  SAO PAULO   ÓLEO DIESEL S10   
4260   2019-06-23  2019-06-29  SUDESTE  SAO PAULO    GASOLINA COMUM   
4261   2019-06-23  2019-06-29  SUDESTE  SAO PAULO               GLP   
4262   2019-06-23  2019-06-29  SUDESTE  SAO PAULO               GNV   

      NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
0                             4047              R$/l                0.768   
1                             4066              R$/l                0.766   
2                             4077              R$/l                0.823   
3                             4073              R$/l                0.887   
4                             4082              R$/l                0.894   
...                            ...               ...                  ...   
4258                           863              R$/l                3.448   
4259                          1277              R$/l                3.574   
4260                          1644              R$/l                4.142   
4261                          1017           R$/13Kg               66.893   
4262                            52             R$/m3                3.020   

      DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
0                     0.085                 0.590                 1.150   
1                     0.083                 0.590                 1.150   
2                     0.071                 0.620                 1.199   
3                     0.075                 0.639                 1.359   
4                     0.071                 0.669                 1.199   
...                     ...                   ...                   ...   
4258                  0.156                 3.099                 4.220   
4259                  0.169                 3.199                 4.320   
4260                  0.183                 3.769                 4.999   
4261                  6.100                50.000                89.900   
4262                  0.229                 2.699                 3.490   

     MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA PREÇO MÉDIO DISTRIBUIÇÃO  \
0                   0.198                     0.111                     0.57   
1                    0.19                     0.108                    0.576   
2                   0.209                     0.086                    0.614   
3                   0.216                     0.085                    0.671   
4                   0.205                     0.079                    0.689   
...                   ...                       ...                      ...   
4258                0.401                     0.045                    3.047   
4259                0.451                     0.047                    3.123   
4260                0.429                     0.044                    3.713   
4261               17.679                     0.091                   49.214   
4262                0.646                     0.076                    2.374   

     DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                         0.056                    0.4271   
1                          0.05                   0.43204   
2                         0.063                   0.34951   
3                         0.075                    0.3398   
4                         0.072                   0.47797   

**Selecionando registros de postos do Rio de Janeiro com preços acima de 2 reais**

In [119]:
data['ESTADO'] == 'RIO DE JANEIRO'

0         False
1         False
2         False
3         False
4         False
          ...  
106818    False
106819    False
106820    False
106821    False
106822    False
Name: ESTADO, Length: 106823, dtype: bool

In [120]:
data['PREÇO MÉDIO REVENDA'] > 2.0

0         False
1         False
2         False
3         False
4         False
          ...  
106818     True
106819     True
106820     True
106821     True
106822     True
Name: PREÇO MÉDIO REVENDA, Length: 106823, dtype: bool

In [121]:
selecao = (data['ESTADO'] == 'RIO DE JANEIRO') & (data['PREÇO MÉDIO REVENDA'] > 2.0)
selecao

0         False
1         False
2         False
3         False
4         False
          ...  
106818    False
106819    False
106820    False
106821    False
106822    False
Length: 106823, dtype: bool

Note que o resultado da seleção continua sendo uma _Series de boobleans_ com o _mesmo número de linhas/observações do DF_, de modo que cada linha possuirá um valor boobleano indicando se o posto é do Rio de Janeiro **E** o preço aferido do combustível é maior que 2 reais (True) ou não (False).</br>
O símbolo **&** significa **AND** na comparação. Essa nomenclatura do python/pandas é diferente das nomenclaturas tradicionais (&&).
Similarmente:
- **|** representa o **OR** (não é ||)
- **~** representa o **NOT** (não é !)

In [122]:
data[selecao].reset_index(drop=True)

DATA INICIAL  DATA FINAL   REGIÃO          ESTADO           PRODUTO  \
0      2006-02-26  2006-03-04  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
1      2006-03-05  2006-03-11  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
2      2006-03-12  2006-03-18  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
3      2006-03-19  2006-03-25  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
4      2006-03-26  2006-04-01  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
...           ...         ...      ...             ...               ...   
3049   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO       ÓLEO DIESEL   
3050   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO   ÓLEO DIESEL S10   
3051   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO    GASOLINA COMUM   
3052   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO               GLP   
3053   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO               GNV   

      NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
0                              881              R$/l                2.028   
1                              889              R$/l                2.125   
2                              902              R$/l                2.163   
3                              898              R$/l                2.166   
4                              890              R$/l                2.172   
...                            ...               ...                  ...   
3049                           212              R$/l                3.569   
3050                           335              R$/l                3.697   
3051                           422              R$/l                4.928   
3052                           221           R$/13Kg               65.010   
3053                           124             R$/m3                3.111   

      DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
0                     0.148                 1.589                 2.550   
1                     0.149                 1.779                 2.550   
2                     0.138                 1.799                 2.599   
3                     0.146                 1.760                 2.568   
4                     0.143                 1.789                 2.550   
...                     ...                   ...                   ...   
3049                  0.166                 3.179                 4.059   
3050                  0.187                 3.279                 4.389   
3051                  0.165                 4.599                 5.859   
3052                  5.812                50.000                79.000   
3053                  0.260                 2.799                 3.799   

     MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA PREÇO MÉDIO DISTRIBUIÇÃO  \
0                   0.222                     0.073                    1.806   
1                   0.286                     0.070                    1.839   
2                   0.268                     0.064                    1.895   
3                   0.231                     0.067                    1.935   
4                   0.209                     0.066                    1.963   
...                   ...                       ...                      ...   
3049                0.467                     0.047                    3.102   
3050                  0.5                     0.051                    3.197   
3051                0.538                     0.033                     4.39   
3052               17.475                     0.089                   47.535   
3053                0.707                     0.084                    2.404   

     DESVIO PADRÃO DISTRIBUIÇÃO PREÇO MÍNIMO DISTRIBUIÇÃO  \
0                          0.11                      1.31   
1                         0.117                     1.438   
2                         0.134                      1.43   
3                          0.14                     1.438   


Alternativamente, poderíamos usar o método `query` para fazermos tal seleção. Porém, isso não é possível especificamente para esse, caso pois o rótulo da coluna 'PREÇO MÉDIO REVENDA' possui caracteres inválidos para o método.

In [123]:
# data.query('ESTADO =="RIO DE JANEIRO" and PREÇO MÉDIO REVENDA > 2.0')

**Aprofundando mais ainda**

A primeira comparação `(data['ESTADO'] == 'RIO DE JANEIRO')` checa, linha a linha (amostra a amostra) do DataFrame, quais são aquelas cujo o estado é RIO DE JANEIRO. Nenhuma averiguação de preços é feita nesse momento. Como resultado, temos uma Series de booleans que responde **apenas** a essa "pergunta" feita.

A segunda comparação `(data['PREÇO MÉDIO REVENDA'] > 2)` checa, linha a linha (amostra a amostra) do DataFrame, quais são os registro cujo preço do combustível é maior que 2 reais. Note que essa comparação checará os postos de **TODOS os estados**. Como resultado, temos uma Series de booleans que responde **apenas** a essa "pergunta" feita.

Por fim, as duas "perguntas" são unidas pelo AND (&) que retorna a "pergunta completa" que fizemos.

Alguns podem argumentar que tal abordagem é **ineficiente**, uma vez que, para cada condição ("pergunta"), estamos varrendo todas as linhas do DataFrame.
O Pandas tenta otimizar isso ao máximo por de trás dos panos. Mas, de fato, de tivermos um dataset muito grande (centenas de milhares de linhas), tal abordagem se tornará lenta.

Assim, poderíamos fazer filtragem com múltiplos condicionais em partes:

In [125]:
selecao_1 = data['ESTADO'] == 'RIO DE JANEIRO'
postos_rj = data[selecao_1]
postos_rj

DATA INICIAL  DATA FINAL   REGIÃO          ESTADO           PRODUTO  \
22       2004-05-09  2004-05-15  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
49       2004-05-16  2004-05-22  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
76       2004-05-23  2004-05-29  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
103      2004-05-30  2004-06-05  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
130      2004-06-06  2004-06-12  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
...             ...         ...      ...             ...               ...   
106718   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO       ÓLEO DIESEL   
106745   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO   ÓLEO DIESEL S10   
106772   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO    GASOLINA COMUM   
106799   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO               GLP   
106817   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO               GNV   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
22                               952              R$/l                1.098   
49                               948              R$/l                1.092   
76                               973              R$/l                1.103   
103                              955              R$/l                1.149   
130                              966              R$/l                1.165   
...                              ...               ...                  ...   
106718                           212              R$/l                3.569   
106745                           335              R$/l                3.697   
106772                           422              R$/l                4.928   
106799                           221           R$/13Kg               65.010   
106817                           124             R$/m3                3.111   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
22                      0.154                 0.740                 1.890   
49                      0.157                 0.740                 1.499   
76                      0.140                 0.770                 1.589   
103                     0.156                 0.799                 1.599   
130                     0.154                 0.830                 1.599   
...                       ...                   ...                   ...   
106718                  0.166                 3.179                 4.059   
106745                  0.187                 3.279                 4.389   
106772                  0.165                 4.599                 5.859   
106799                  5.812                50.000                79.000   
106817                  0.260                 2.799                 3.799   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
22                    0.312                     0.140   
49                    0.284                     0.144   
76                    0.281                     0.127   
103                     0.3                     0.136   
130                   0.254                     0.132   
...                     ...                       ...   
106718                0.467                     0.047   
106745                  0.5                     0.051   
106772                0.538                     0.033   
106799               17.475                     0.089   
106817                0.707                     0.084   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
22                        0.786                      0.173   
49                        0.808                      0.175   
76                        0.822                      0.166   
103                       0.849                      0.188   
130                       0.911                      0.198   
...                         ...                        ...   
106718                    3.102                      0.119   
106745         

In [126]:
selecao_2 = postos_rj['PREÇO MÉDIO REVENDA'] > 2.0
selecao_2

22        False
49        False
76        False
103       False
130       False
          ...  
106718     True
106745     True
106772     True
106799     True
106817     True
Name: PREÇO MÉDIO REVENDA, Length: 4263, dtype: bool

In [128]:
postos_rj_preco_maior_que_2 = postos_rj[selecao_2]
postos_rj_preco_maior_que_2

DATA INICIAL  DATA FINAL   REGIÃO          ESTADO           PRODUTO  \
2501     2006-02-26  2006-03-04  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
2528     2006-03-05  2006-03-11  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
2555     2006-03-12  2006-03-18  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
2582     2006-03-19  2006-03-25  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
2609     2006-03-26  2006-04-01  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
...             ...         ...      ...             ...               ...   
106718   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO       ÓLEO DIESEL   
106745   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO   ÓLEO DIESEL S10   
106772   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO    GASOLINA COMUM   
106799   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO               GLP   
106817   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO               GNV   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
2501                             881              R$/l                2.028   
2528                             889              R$/l                2.125   
2555                             902              R$/l                2.163   
2582                             898              R$/l                2.166   
2609                             890              R$/l                2.172   
...                              ...               ...                  ...   
106718                           212              R$/l                3.569   
106745                           335              R$/l                3.697   
106772                           422              R$/l                4.928   
106799                           221           R$/13Kg               65.010   
106817                           124             R$/m3                3.111   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
2501                    0.148                 1.589                 2.550   
2528                    0.149                 1.779                 2.550   
2555                    0.138                 1.799                 2.599   
2582                    0.146                 1.760                 2.568   
2609                    0.143                 1.789                 2.550   
...                       ...                   ...                   ...   
106718                  0.166                 3.179                 4.059   
106745                  0.187                 3.279                 4.389   
106772                  0.165                 4.599                 5.859   
106799                  5.812                50.000                79.000   
106817                  0.260                 2.799                 3.799   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
2501                  0.222                     0.073   
2528                  0.286                     0.070   
2555                  0.268                     0.064   
2582                  0.231                     0.067   
2609                  0.209                     0.066   
...                     ...                       ...   
106718                0.467                     0.047   
106745                  0.5                     0.051   
106772                0.538                     0.033   
106799               17.475                     0.089   
106817                0.707                     0.084   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
2501                      1.806                       0.11   
2528                      1.839                      0.117   
2555                      1.895                      0.134   
2582                      1.935                       0.14   
2609                      1.963                      0.133   
...                         ...                        ...   
106718                    3.102                      0.119   
106745         

**Selecionando registros de postos de São Paulo ou do Rio de Janeiro com Gasolina Comum acima de 2 reais**</br>
Podemos fazer a solução do "jeito mais lento", percorrendo o DataFrame inteiro múltiplas vezes:

In [137]:
selecao_1 = (data['ESTADO'] == 'SAO PAULO') | (data['ESTADO'] == 'RIO DE JANEIRO')
selecao_1

0         False
1         False
2         False
3         False
4         False
          ...  
106818    False
106819    False
106820    False
106821     True
106822    False
Name: ESTADO, Length: 106823, dtype: bool

In [140]:
selecao_2 = (data['PRODUTO'] == 'GASOLINA COMUM') & (data['PREÇO MÉDIO REVENDA'] > 2.0)
selecao_2

0         False
1         False
2         False
3         False
4         False
          ...  
106818    False
106819    False
106820    False
106821    False
106822    False
Length: 106823, dtype: bool

In [141]:
selecao_final = selecao_1 & selecao_2 
data[selecao_final]

DATA INICIAL  DATA FINAL   REGIÃO          ESTADO         PRODUTO  \
12086    2004-05-09  2004-05-15  SUDESTE  RIO DE JANEIRO  GASOLINA COMUM   
12113    2004-05-16  2004-05-22  SUDESTE  RIO DE JANEIRO  GASOLINA COMUM   
12140    2004-05-23  2004-05-29  SUDESTE  RIO DE JANEIRO  GASOLINA COMUM   
12167    2004-05-30  2004-06-05  SUDESTE  RIO DE JANEIRO  GASOLINA COMUM   
12194    2004-06-06  2004-06-12  SUDESTE  RIO DE JANEIRO  GASOLINA COMUM   
...             ...         ...      ...             ...             ...   
106479   2019-06-09  2019-06-15  SUDESTE       SAO PAULO  GASOLINA COMUM   
106623   2019-06-16  2019-06-22  SUDESTE  RIO DE JANEIRO  GASOLINA COMUM   
106629   2019-06-16  2019-06-22  SUDESTE       SAO PAULO  GASOLINA COMUM   
106772   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO  GASOLINA COMUM   
106778   2019-06-23  2019-06-29  SUDESTE       SAO PAULO  GASOLINA COMUM   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
12086                           1071              R$/l                2.045   
12113                           1055              R$/l                2.040   
12140                           1091              R$/l                2.042   
12167                           1055              R$/l                2.053   
12194                           1091              R$/l                2.063   
...                              ...               ...                  ...   
106479                          1643              R$/l                4.210   
106623                           418              R$/l                4.927   
106629                          1635              R$/l                4.168   
106772                           422              R$/l                4.928   
106778                          1644              R$/l                4.142   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
12086                   0.109                 1.700                 2.599   
12113                   0.113                 1.700                 2.599   
12140                   0.108                 1.700                 2.599   
12167                   0.111                 1.730                 2.599   
12194                   0.107                 1.760                 2.599   
...                       ...                   ...                   ...   
106479                  0.177                 3.759                 4.992   
106623                  0.160                 4.599                 5.859   
106629                  0.177                 3.679                 5.199   
106772                  0.165                 4.599                 5.859   
106778                  0.183                 3.769                 4.999   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
12086                 0.254                     0.053   
12113                 0.252                     0.055   
12140                 0.252                     0.053   
12167                 0.251                     0.054   
12194                 0.247                     0.052   
...                     ...                       ...   
106479                0.425                     0.042   
106623                0.544                     0.032   
106629                0.443                     0.042   
106772                0.538                     0.033   
106778                0.429                     0.044   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
12086                     1.791                      0.047   
12113                     1.788                      0.049   
12140                      1.79                      0.046   
12167                     1.802                      0.055   
12194                     1.816                      0.054   
...                         ...                        ...   
106479                    3.785                      0.096   
106623                    4.383        

Alternativamente:

In [149]:
selecao_1 = (data['ESTADO'] == 'SAO PAULO') | (data['ESTADO'] == 'RIO DE JANEIRO')
postos_sp_rj = data[selecao_1]
postos_sp_rj

DATA INICIAL  DATA FINAL   REGIÃO          ESTADO           PRODUTO  \
22       2004-05-09  2004-05-15  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
23       2004-05-09  2004-05-15  SUDESTE       SAO PAULO  ETANOL HIDRATADO   
49       2004-05-16  2004-05-22  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
50       2004-05-16  2004-05-22  SUDESTE       SAO PAULO  ETANOL HIDRATADO   
76       2004-05-23  2004-05-29  SUDESTE  RIO DE JANEIRO  ETANOL HIDRATADO   
...             ...         ...      ...             ...               ...   
106778   2019-06-23  2019-06-29  SUDESTE       SAO PAULO    GASOLINA COMUM   
106799   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO               GLP   
106805   2019-06-23  2019-06-29  SUDESTE       SAO PAULO               GLP   
106817   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO               GNV   
106821   2019-06-23  2019-06-29  SUDESTE       SAO PAULO               GNV   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
22                               952              R$/l                1.098   
23                              4047              R$/l                0.768   
49                               948              R$/l                1.092   
50                              4066              R$/l                0.766   
76                               973              R$/l                1.103   
...                              ...               ...                  ...   
106778                          1644              R$/l                4.142   
106799                           221           R$/13Kg               65.010   
106805                          1017           R$/13Kg               66.893   
106817                           124             R$/m3                3.111   
106821                            52             R$/m3                3.020   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
22                      0.154                 0.740                 1.890   
23                      0.085                 0.590                 1.150   
49                      0.157                 0.740                 1.499   
50                      0.083                 0.590                 1.150   
76                      0.140                 0.770                 1.589   
...                       ...                   ...                   ...   
106778                  0.183                 3.769                 4.999   
106799                  5.812                50.000                79.000   
106805                  6.100                50.000                89.900   
106817                  0.260                 2.799                 3.799   
106821                  0.229                 2.699                 3.490   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
22                    0.312                     0.140   
23                    0.198                     0.111   
49                    0.284                     0.144   
50                     0.19                     0.108   
76                    0.281                     0.127   
...                     ...                       ...   
106778                0.429                     0.044   
106799               17.475                     0.089   
106805               17.679                     0.091   
106817                0.707                     0.084   
106821                0.646                     0.076   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
22                        0.786                      0.173   
23                         0.57                      0.056   
49                        0.808                      0.175   
50                        0.576                       0.05   
76                        0.822                      0.166   
...                         ...                        ...   
106778                    3.713                      0.097   
106799         

In [150]:
selecao_2 = (postos_sp_rj['PRODUTO'] == 'GASOLINA COMUM') & (postos_sp_rj['PREÇO MÉDIO REVENDA'] > 2.0)
selecao_2

22        False
23        False
49        False
50        False
76        False
          ...  
106778     True
106799    False
106805    False
106817    False
106821    False
Length: 8526, dtype: bool

In [153]:
postos_sp_rj[selecao_2]

DATA INICIAL  DATA FINAL   REGIÃO          ESTADO         PRODUTO  \
12086    2004-05-09  2004-05-15  SUDESTE  RIO DE JANEIRO  GASOLINA COMUM   
12113    2004-05-16  2004-05-22  SUDESTE  RIO DE JANEIRO  GASOLINA COMUM   
12140    2004-05-23  2004-05-29  SUDESTE  RIO DE JANEIRO  GASOLINA COMUM   
12167    2004-05-30  2004-06-05  SUDESTE  RIO DE JANEIRO  GASOLINA COMUM   
12194    2004-06-06  2004-06-12  SUDESTE  RIO DE JANEIRO  GASOLINA COMUM   
...             ...         ...      ...             ...             ...   
106479   2019-06-09  2019-06-15  SUDESTE       SAO PAULO  GASOLINA COMUM   
106623   2019-06-16  2019-06-22  SUDESTE  RIO DE JANEIRO  GASOLINA COMUM   
106629   2019-06-16  2019-06-22  SUDESTE       SAO PAULO  GASOLINA COMUM   
106772   2019-06-23  2019-06-29  SUDESTE  RIO DE JANEIRO  GASOLINA COMUM   
106778   2019-06-23  2019-06-29  SUDESTE       SAO PAULO  GASOLINA COMUM   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
12086                           1071              R$/l                2.045   
12113                           1055              R$/l                2.040   
12140                           1091              R$/l                2.042   
12167                           1055              R$/l                2.053   
12194                           1091              R$/l                2.063   
...                              ...               ...                  ...   
106479                          1643              R$/l                4.210   
106623                           418              R$/l                4.927   
106629                          1635              R$/l                4.168   
106772                           422              R$/l                4.928   
106778                          1644              R$/l                4.142   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
12086                   0.109                 1.700                 2.599   
12113                   0.113                 1.700                 2.599   
12140                   0.108                 1.700                 2.599   
12167                   0.111                 1.730                 2.599   
12194                   0.107                 1.760                 2.599   
...                       ...                   ...                   ...   
106479                  0.177                 3.759                 4.992   
106623                  0.160                 4.599                 5.859   
106629                  0.177                 3.679                 5.199   
106772                  0.165                 4.599                 5.859   
106778                  0.183                 3.769                 4.999   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
12086                 0.254                     0.053   
12113                 0.252                     0.055   
12140                 0.252                     0.053   
12167                 0.251                     0.054   
12194                 0.247                     0.052   
...                     ...                       ...   
106479                0.425                     0.042   
106623                0.544                     0.032   
106629                0.443                     0.042   
106772                0.538                     0.033   
106778                0.429                     0.044   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
12086                     1.791                      0.047   
12113                     1.788                      0.049   
12140                      1.79                      0.046   
12167                     1.802                      0.055   
12194                     1.816                      0.054   
...                         ...                        ...   
106479                    3.785                      0.096   
106623                    4.383        

**Selecionando registros dos anos de 2008, 2010 e 2012**

In [155]:
selecao = (data['ANO'] == 2008) | (data['ANO'] == 2010) | (data['ANO'] == 2012)
data[selecao]['ANO'].unique()

array([2008, 2010, 2012], dtype=int64)

Alternativamente:

In [158]:
lista = [2008, 2010, 2012]

filtro = data['ANO'].isin(lista) # Retorna uma Series de booleanos
data[filtro]['ANO'].unique()

array([2008, 2010, 2012], dtype=int64)

Alternativamente:

In [159]:
data.query('ANO  in @lista')

DATA INICIAL  DATA FINAL        REGIÃO               ESTADO  \
5098    2008-01-06  2008-01-12  CENTRO OESTE     DISTRITO FEDERAL   
5099    2008-01-06  2008-01-12  CENTRO OESTE                GOIAS   
5100    2008-01-06  2008-01-12  CENTRO OESTE          MATO GROSSO   
5101    2008-01-06  2008-01-12  CENTRO OESTE   MATO GROSSO DO SUL   
5102    2008-01-06  2008-01-12      NORDESTE              ALAGOAS   
...            ...         ...           ...                  ...   
55754   2012-12-30  2013-01-05      NORDESTE  RIO GRANDE DO NORTE   
55755   2012-12-30  2013-01-05           SUL    RIO GRANDE DO SUL   
55756   2012-12-30  2013-01-05           SUL       SANTA CATARINA   
55757   2012-12-30  2013-01-05       SUDESTE            SAO PAULO   
55758   2012-12-30  2013-01-05      NORDESTE              SERGIPE   

                PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
5098   ETANOL HIDRATADO                            80              R$/l   
5099   ETANOL HIDRATADO                           255              R$/l   
5100   ETANOL HIDRATADO                           142              R$/l   
5101   ETANOL HIDRATADO                           133              R$/l   
5102   ETANOL HIDRATADO                            97              R$/l   
...                 ...                           ...               ...   
55754               GNV                            17             R$/m3   
55755               GNV                            34             R$/m3   
55756               GNV                            41             R$/m3   
55757               GNV                            82             R$/m3   
55758               GNV                            11             R$/m3   

       PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
5098                 1.806                  0.082                 1.709   
5099                 1.616                  0.100                 1.470   
5100                 1.581                  0.095                 1.390   
5101                 1.831                  0.046                 1.680   
5102                 1.699                  0.098                 1.530   
...                    ...                    ...                   ...   
55754                1.891                  0.015                 1.860   
55755                1.980                  0.040                 1.919   
55756                2.003                  0.034                 1.879   
55757                1.598                  0.199                 1.399   
55758                1.847                  0.033                 1.790   

       PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
5098                  1.950                 0.29                     0.045   
5099                  1.899                0.293                     0.062   
5100                  1.850                0.278                     0.060   
5101                  1.910                0.382                     0.025   
5102                  1.999                0.199                     0.058   
...                     ...                  ...                       ...   
55754                 1.900                0.466                     0.008   
55755                 2.140                0.566                     0.020   
55756                 2.099                    -                     0.017   
55757                 2.599                0.397                     0.125   
55758                 1.899                0.504                     0.018   

      PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
5098                     1.516                      0.061   
5099                     1.323                       0.05   
5100                     1.303                      0.073   
5101                     1.449                      0.044   
5102                       1.5                      0.062   
...                        ...                        ...   
55754      

**Iterando com DataFrames**</br>
For-each `DataFrame.iterrows()` (LENTO ==> apenas indicado para iterar pequenos conjunto de dados)

In [160]:
for index, row in data.head(10).iterrows():
    print(f'indice {index} ==> {row["ESTADO"]}')

indice 0 ==> DISTRITO FEDERAL
indice 1 ==> GOIAS
indice 2 ==> MATO GROSSO
indice 3 ==> MATO GROSSO DO SUL
indice 4 ==> ALAGOAS
indice 5 ==> BAHIA
indice 6 ==> CEARA
indice 7 ==> MARANHAO
indice 8 ==> PARAIBA
indice 9 ==> PERNAMBUCO


### 2. Preparação dos dados

In [161]:
data

DATA INICIAL  DATA FINAL        REGIÃO               ESTADO  \
0        2004-05-09  2004-05-15  CENTRO OESTE     DISTRITO FEDERAL   
1        2004-05-09  2004-05-15  CENTRO OESTE                GOIAS   
2        2004-05-09  2004-05-15  CENTRO OESTE          MATO GROSSO   
3        2004-05-09  2004-05-15  CENTRO OESTE   MATO GROSSO DO SUL   
4        2004-05-09  2004-05-15      NORDESTE              ALAGOAS   
...             ...         ...           ...                  ...   
106818   2019-06-23  2019-06-29      NORDESTE  RIO GRANDE DO NORTE   
106819   2019-06-23  2019-06-29           SUL    RIO GRANDE DO SUL   
106820   2019-06-23  2019-06-29           SUL       SANTA CATARINA   
106821   2019-06-23  2019-06-29       SUDESTE            SAO PAULO   
106822   2019-06-23  2019-06-29      NORDESTE              SERGIPE   

                 PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0       ETANOL HIDRATADO                           127              R$/l   
1       ETANOL HIDRATADO                           387              R$/l   
2       ETANOL HIDRATADO                           192              R$/l   
3       ETANOL HIDRATADO                           162              R$/l   
4       ETANOL HIDRATADO                           103              R$/l   
...                  ...                           ...               ...   
106818               GNV                             7             R$/m3   
106819               GNV                            23             R$/m3   
106820               GNV                            24             R$/m3   
106821               GNV                            52             R$/m3   
106822               GNV                             4             R$/m3   

        PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                     1.288                  0.016                 1.190   
1                     1.162                  0.114                 0.890   
2                     1.389                  0.097                 1.180   
3                     1.262                  0.070                 1.090   
4                     1.181                  0.078                 1.050   
...                     ...                    ...                   ...   
106818                3.574                  0.065                 3.499   
106819                3.401                  0.129                 3.230   
106820                2.912                  0.190                 2.699   
106821                3.020                  0.229                 2.699   
106822                3.697                  0.005                 3.689   

        PREÇO MÁXIMO REVENDA MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                      1.350                0.463                     0.012   
1                      1.449                0.399                     0.098   
2                      1.760                0.419                     0.070   
3                      1.509                0.432                     0.055   
4                      1.400                 0.24                     0.066   
...                      ...                  ...                       ...   
106818                 3.690                0.818                     0.018   
106819                 3.789                 0.95                     0.038   
106820                 3.499                0.914                     0.065   
106821                 3.490                0.646                     0.076   
106822                 3.699                1.179                     0.001   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                         0.825                       0.11   
1                         0.763                      0.088   
2                          0.97                      0.095   
3                          0.83                      0.119   
4                         0.941                      0.077   
...                

#### 2.1 Tratando observações com valores vazios (null / NaN) no dataset

In [162]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype  
---  ------                         --------------   -----  
 0   DATA INICIAL                   106823 non-null  object 
 1   DATA FINAL                     106823 non-null  object 
 2   REGIÃO                         106823 non-null  object 
 3   ESTADO                         106823 non-null  object 
 4   PRODUTO                        106823 non-null  object 
 5   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64  
 6   UNIDADE DE MEDIDA              106823 non-null  object 
 7   PREÇO MÉDIO REVENDA            106823 non-null  float64
 8   DESVIO PADRÃO REVENDA          106823 non-null  float64
 9   PREÇO MÍNIMO REVENDA           106823 non-null  float64
 10  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 11  MARGEM MÉDIA REVENDA           106823 non-null  object 
 12  COEF DE VARIAÇÃO REVENDA      

De um total de 106823 observações, **não há valores null / NaN** para nenhum atributo. Mas, veremos que não é bem assim neste caso específico.

#### 2.2 Conversão de tipos de atributos
O pandas automaticamente reconhece os tipos de dados de cada coluna.
Porém, existem alguns atributos que estão com seus tipos errados: P. ex., "PREÇO MÉDIO DISTRIBUIÇÃO" deveria ser `float64` e não `object`.
Nestes casos, muito provavelmente algumas amostras têm um string ao invés de um número para tais atributos.

Os atributos "DATA INICIAL" e "DATA FINAL" deveriam ser do tipo `datetime`.

Em outros casos, alguns atributos categóricos são `objects`, mas poderiam ter o tipo `category`, que é um tipo especial do pandas.
Este tipo é necessário para se utilizar algumas funções específicas do pandas.
Não converteremos para este tipo por ora.

In [164]:
data_pre = data.copy()

**Datas**
Como os atributos de data do dataset já estão em um formato de data aceitável (YYYY-MM-DD), não precisamos forçar nenhuma conversão nesse sentido.

In [166]:
data_pre['DATA INICIAL'] = pd.to_datetime(data_pre['DATA INICIAL'])
data_pre['DATA FINAL'] = pd.to_datetime(data_pre['DATA FINAL'])

In [167]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype         
---  ------                         --------------   -----         
 0   DATA INICIAL                   106823 non-null  datetime64[ns]
 1   DATA FINAL                     106823 non-null  datetime64[ns]
 2   REGIÃO                         106823 non-null  object        
 3   ESTADO                         106823 non-null  object        
 4   PRODUTO                        106823 non-null  object        
 5   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64         
 6   UNIDADE DE MEDIDA              106823 non-null  object        
 7   PREÇO MÉDIO REVENDA            106823 non-null  float64       
 8   DESVIO PADRÃO REVENDA          106823 non-null  float64       
 9   PREÇO MÍNIMO REVENDA           106823 non-null  float64       
 10  PREÇO MÁXIMO REVENDA           106823 non-null  float64       
 11  

**Dados Numéricos**

In [168]:
# Convertendo atributos/colunas para `numeric`
for colunas in['MARGEM MÉDIA REVENDA','PREÇO MÉDIO DISTRIBUIÇÃO','DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO', 'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO']:
    """errors{ignore, raise, coerce}, o padrão raise
        Se raise, a análise inválida gerará uma exceção.
        Se coerce, então a análise inválida será definida como NaN.
        Se ignore, então a análise inválida retornará a entrada."""

    data_pre[colunas] = pd.to_numeric(data_pre[colunas], errors='coerce')

In [169]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype         
---  ------                         --------------   -----         
 0   DATA INICIAL                   106823 non-null  datetime64[ns]
 1   DATA FINAL                     106823 non-null  datetime64[ns]
 2   REGIÃO                         106823 non-null  object        
 3   ESTADO                         106823 non-null  object        
 4   PRODUTO                        106823 non-null  object        
 5   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64         
 6   UNIDADE DE MEDIDA              106823 non-null  object        
 7   PREÇO MÉDIO REVENDA            106823 non-null  float64       
 8   DESVIO PADRÃO REVENDA          106823 non-null  float64       
 9   PREÇO MÍNIMO REVENDA           106823 non-null  float64       
 10  PREÇO MÁXIMO REVENDA           106823 non-null  float64       
 11  

Note que temos vários valores ***null*** agora após a ***conversão de tipos***. Vamos checá-los com mais cuidado nos dados originais e preprocessados.

#### 2.3 Limpeza de dados

In [181]:
mask = data_pre['MARGEM MÉDIA REVENDA'].isnull()
mask

0         False
1         False
2         False
3         False
4         False
          ...  
106818    False
106819    False
106820    False
106821    False
106822    False
Name: MARGEM MÉDIA REVENDA, Length: 106823, dtype: bool

In [182]:
data_pre[mask]

DATA INICIAL DATA FINAL   REGIÃO          ESTADO           PRODUTO  \
1903     2005-09-25 2005-10-01    NORTE            PARA  ETANOL HIDRATADO   
1958     2005-10-09 2005-10-15    NORTE         RORAIMA  ETANOL HIDRATADO   
2012     2005-10-23 2005-10-29    NORTE         RORAIMA  ETANOL HIDRATADO   
2497     2006-02-26 2006-03-04    NORTE         RORAIMA  ETANOL HIDRATADO   
3199     2006-08-27 2006-09-02    NORTE         RORAIMA  ETANOL HIDRATADO   
...             ...        ...      ...             ...               ...   
106664   2019-06-16 2019-06-22  SUDESTE    MINAS GERAIS               GNV   
106666   2019-06-16 2019-06-22      SUL          PARANA               GNV   
106811   2019-06-23 2019-06-29  SUDESTE  ESPIRITO SANTO               GNV   
106813   2019-06-23 2019-06-29  SUDESTE    MINAS GERAIS               GNV   
106815   2019-06-23 2019-06-29      SUL          PARANA               GNV   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
1903                               2              R$/l                1.694   
1958                               3              R$/l                2.000   
2012                               3              R$/l                2.277   
2497                              11              R$/l                2.182   
3199                              22              R$/l                2.285   
...                              ...               ...                  ...   
106664                             5             R$/m3                3.445   
106666                             7             R$/m3                3.132   
106811                             4             R$/m3                3.299   
106813                             6             R$/m3                3.548   
106815                             1             R$/m3                3.290   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
1903                    0.283                 1.690                 2.090   
1958                    0.000                 2.000                 2.000   
2012                    0.023                 2.250                 2.290   
2497                    0.040                 2.100                 2.200   
3199                    0.068                 1.980                 2.300   
...                       ...                   ...                   ...   
106664                  0.147                 3.347                 3.699   
106666                  0.295                 3.049                 3.890   
106811                  0.005                 3.290                 3.299   
106813                  0.100                 3.495                 3.699   
106815                  0.000                 3.290                 3.290   

        MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
1903                     NaN                     0.167   
1958                     NaN                     0.000   
2012                     NaN                     0.010   
2497                     NaN                     0.018   
3199                     NaN                     0.030   
...                      ...                       ...   
106664                   NaN                     0.043   
106666                   NaN                     0.094   
106811                   NaN                     0.002   
106813                   NaN                     0.028   
106815                   NaN                     0.000   

        PREÇO MÉDIO DISTRIBUIÇÃO  DESVIO PADRÃO DISTRIBUIÇÃO  \
1903                         NaN                         NaN   
1958                         NaN                         NaN   
2012                         NaN                         NaN   
2497                         NaN                         NaN   
3199                         NaN                         NaN   
...                          ...                         ...   
106664                       NaN                         NaN   

In [183]:
# Nos dados originais, quais eram os valores de PREÇO MÉDIO DISTRIBUIÇÃO dos registros que agora possuem valores NaN
data[mask]

DATA INICIAL  DATA FINAL   REGIÃO          ESTADO           PRODUTO  \
1903     2005-09-25  2005-10-01    NORTE            PARA  ETANOL HIDRATADO   
1958     2005-10-09  2005-10-15    NORTE         RORAIMA  ETANOL HIDRATADO   
2012     2005-10-23  2005-10-29    NORTE         RORAIMA  ETANOL HIDRATADO   
2497     2006-02-26  2006-03-04    NORTE         RORAIMA  ETANOL HIDRATADO   
3199     2006-08-27  2006-09-02    NORTE         RORAIMA  ETANOL HIDRATADO   
...             ...         ...      ...             ...               ...   
106664   2019-06-16  2019-06-22  SUDESTE    MINAS GERAIS               GNV   
106666   2019-06-16  2019-06-22      SUL          PARANA               GNV   
106811   2019-06-23  2019-06-29  SUDESTE  ESPIRITO SANTO               GNV   
106813   2019-06-23  2019-06-29  SUDESTE    MINAS GERAIS               GNV   
106815   2019-06-23  2019-06-29      SUL          PARANA               GNV   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
1903                               2              R$/l                1.694   
1958                               3              R$/l                2.000   
2012                               3              R$/l                2.277   
2497                              11              R$/l                2.182   
3199                              22              R$/l                2.285   
...                              ...               ...                  ...   
106664                             5             R$/m3                3.445   
106666                             7             R$/m3                3.132   
106811                             4             R$/m3                3.299   
106813                             6             R$/m3                3.548   
106815                             1             R$/m3                3.290   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
1903                    0.283                 1.690                 2.090   
1958                    0.000                 2.000                 2.000   
2012                    0.023                 2.250                 2.290   
2497                    0.040                 2.100                 2.200   
3199                    0.068                 1.980                 2.300   
...                       ...                   ...                   ...   
106664                  0.147                 3.347                 3.699   
106666                  0.295                 3.049                 3.890   
106811                  0.005                 3.290                 3.299   
106813                  0.100                 3.495                 3.699   
106815                  0.000                 3.290                 3.290   

       MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
1903                      -                     0.167   
1958                      -                     0.000   
2012                      -                     0.010   
2497                      -                     0.018   
3199                      -                     0.030   
...                     ...                       ...   
106664                    -                     0.043   
106666                    -                     0.094   
106811                    -                     0.002   
106813                    -                     0.028   
106815                    -                     0.000   

       PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
1903                          -                          -   
1958                          -                          -   
2012                          -                          -   
2497                          -                          -   
3199                          -                          -   
...                         ...                        ...   
106664                        -                          -   
106666         

Várias amostras possuem a string '-' em algumas colunas ao invés de um número de fato. Ou seja, não há aferições destes atributos para estas amostras.

Poderíamos preencher os valores NaN com um valor padrão. Para isso, basta usar o método `.fillna`.

In [184]:
# Retorna uma cópia do data frame com todos os valores NaN de todas as colunas agora preenchidos com 0
# Para alterar o próprio df, use o argumento `inplace=True`
data_pre_fill = data_pre.fillna(0)
data_pre_fill

DATA INICIAL DATA FINAL        REGIÃO               ESTADO  \
0        2004-05-09 2004-05-15  CENTRO OESTE     DISTRITO FEDERAL   
1        2004-05-09 2004-05-15  CENTRO OESTE                GOIAS   
2        2004-05-09 2004-05-15  CENTRO OESTE          MATO GROSSO   
3        2004-05-09 2004-05-15  CENTRO OESTE   MATO GROSSO DO SUL   
4        2004-05-09 2004-05-15      NORDESTE              ALAGOAS   
...             ...        ...           ...                  ...   
106818   2019-06-23 2019-06-29      NORDESTE  RIO GRANDE DO NORTE   
106819   2019-06-23 2019-06-29           SUL    RIO GRANDE DO SUL   
106820   2019-06-23 2019-06-29           SUL       SANTA CATARINA   
106821   2019-06-23 2019-06-29       SUDESTE            SAO PAULO   
106822   2019-06-23 2019-06-29      NORDESTE              SERGIPE   

                 PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0       ETANOL HIDRATADO                           127              R$/l   
1       ETANOL HIDRATADO                           387              R$/l   
2       ETANOL HIDRATADO                           192              R$/l   
3       ETANOL HIDRATADO                           162              R$/l   
4       ETANOL HIDRATADO                           103              R$/l   
...                  ...                           ...               ...   
106818               GNV                             7             R$/m3   
106819               GNV                            23             R$/m3   
106820               GNV                            24             R$/m3   
106821               GNV                            52             R$/m3   
106822               GNV                             4             R$/m3   

        PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  \
0                     1.288                  0.016                 1.190   
1                     1.162                  0.114                 0.890   
2                     1.389                  0.097                 1.180   
3                     1.262                  0.070                 1.090   
4                     1.181                  0.078                 1.050   
...                     ...                    ...                   ...   
106818                3.574                  0.065                 3.499   
106819                3.401                  0.129                 3.230   
106820                2.912                  0.190                 2.699   
106821                3.020                  0.229                 2.699   
106822                3.697                  0.005                 3.689   

        PREÇO MÁXIMO REVENDA  MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
0                      1.350                 0.463                     0.012   
1                      1.449                 0.399                     0.098   
2                      1.760                 0.419                     0.070   
3                      1.509                 0.432                     0.055   
4                      1.400                 0.240                     0.066   
...                      ...                   ...                       ...   
106818                 3.690                 0.818                     0.018   
106819                 3.789                 0.950                     0.038   
106820                 3.499                 0.914                     0.065   
106821                 3.490                 0.646                     0.076   
106822                 3.699                 1.179                     0.001   

        PREÇO MÉDIO DISTRIBUIÇÃO  DESVIO PADRÃO DISTRIBUIÇÃO  \
0                          0.825                       0.110   
1                          0.763                       0.088   
2                          0.970                       0.095   
3                          0.830                       0.119   
4                          0.941                       0.077   
...    

In [185]:
data_pre_fill[mask] # valores que antes eram NaN agora são 0

DATA INICIAL DATA FINAL   REGIÃO          ESTADO           PRODUTO  \
1903     2005-09-25 2005-10-01    NORTE            PARA  ETANOL HIDRATADO   
1958     2005-10-09 2005-10-15    NORTE         RORAIMA  ETANOL HIDRATADO   
2012     2005-10-23 2005-10-29    NORTE         RORAIMA  ETANOL HIDRATADO   
2497     2006-02-26 2006-03-04    NORTE         RORAIMA  ETANOL HIDRATADO   
3199     2006-08-27 2006-09-02    NORTE         RORAIMA  ETANOL HIDRATADO   
...             ...        ...      ...             ...               ...   
106664   2019-06-16 2019-06-22  SUDESTE    MINAS GERAIS               GNV   
106666   2019-06-16 2019-06-22      SUL          PARANA               GNV   
106811   2019-06-23 2019-06-29  SUDESTE  ESPIRITO SANTO               GNV   
106813   2019-06-23 2019-06-29  SUDESTE    MINAS GERAIS               GNV   
106815   2019-06-23 2019-06-29      SUL          PARANA               GNV   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
1903                               2              R$/l                1.694   
1958                               3              R$/l                2.000   
2012                               3              R$/l                2.277   
2497                              11              R$/l                2.182   
3199                              22              R$/l                2.285   
...                              ...               ...                  ...   
106664                             5             R$/m3                3.445   
106666                             7             R$/m3                3.132   
106811                             4             R$/m3                3.299   
106813                             6             R$/m3                3.548   
106815                             1             R$/m3                3.290   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
1903                    0.283                 1.690                 2.090   
1958                    0.000                 2.000                 2.000   
2012                    0.023                 2.250                 2.290   
2497                    0.040                 2.100                 2.200   
3199                    0.068                 1.980                 2.300   
...                       ...                   ...                   ...   
106664                  0.147                 3.347                 3.699   
106666                  0.295                 3.049                 3.890   
106811                  0.005                 3.290                 3.299   
106813                  0.100                 3.495                 3.699   
106815                  0.000                 3.290                 3.290   

        MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
1903                     0.0                     0.167   
1958                     0.0                     0.000   
2012                     0.0                     0.010   
2497                     0.0                     0.018   
3199                     0.0                     0.030   
...                      ...                       ...   
106664                   0.0                     0.043   
106666                   0.0                     0.094   
106811                   0.0                     0.002   
106813                   0.0                     0.028   
106815                   0.0                     0.000   

        PREÇO MÉDIO DISTRIBUIÇÃO  DESVIO PADRÃO DISTRIBUIÇÃO  \
1903                         0.0                         0.0   
1958                         0.0                         0.0   
2012                         0.0                         0.0   
2497                         0.0                         0.0   
3199                         0.0                         0.0   
...                          ...                         ...   
106664                       0.0                         0.0   

In [188]:
# retorna uma cópia do data frame `data_pre` com todos os valores NaN das colunas:
# 'PREÇO MÉDIO DISTRIBUIÇÃO', 'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO' e 'PREÇO MÁXIMO DISTRIBUIÇÃO', respectivamente, com os valores: 10, 20, 30, 'vazio'.
data_pre_fill = data_pre.fillna(value={
    'PREÇO MÉDIO DISTRIBUIÇÃO': 10,
    'DESVIO PADRÃO DISTRIBUIÇÃO': 20,
    'PREÇO MÍNIMO DISTRIBUIÇÃO': 30,
    'PREÇO MÁXIMO DISTRIBUIÇÃO': 'vazio'
})

In [189]:
data_pre_fill[mask]

DATA INICIAL DATA FINAL   REGIÃO          ESTADO           PRODUTO  \
1903     2005-09-25 2005-10-01    NORTE            PARA  ETANOL HIDRATADO   
1958     2005-10-09 2005-10-15    NORTE         RORAIMA  ETANOL HIDRATADO   
2012     2005-10-23 2005-10-29    NORTE         RORAIMA  ETANOL HIDRATADO   
2497     2006-02-26 2006-03-04    NORTE         RORAIMA  ETANOL HIDRATADO   
3199     2006-08-27 2006-09-02    NORTE         RORAIMA  ETANOL HIDRATADO   
...             ...        ...      ...             ...               ...   
106664   2019-06-16 2019-06-22  SUDESTE    MINAS GERAIS               GNV   
106666   2019-06-16 2019-06-22      SUL          PARANA               GNV   
106811   2019-06-23 2019-06-29  SUDESTE  ESPIRITO SANTO               GNV   
106813   2019-06-23 2019-06-29  SUDESTE    MINAS GERAIS               GNV   
106815   2019-06-23 2019-06-29      SUL          PARANA               GNV   

        NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  PREÇO MÉDIO REVENDA  \
1903                               2              R$/l                1.694   
1958                               3              R$/l                2.000   
2012                               3              R$/l                2.277   
2497                              11              R$/l                2.182   
3199                              22              R$/l                2.285   
...                              ...               ...                  ...   
106664                             5             R$/m3                3.445   
106666                             7             R$/m3                3.132   
106811                             4             R$/m3                3.299   
106813                             6             R$/m3                3.548   
106815                             1             R$/m3                3.290   

        DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA  PREÇO MÁXIMO REVENDA  \
1903                    0.283                 1.690                 2.090   
1958                    0.000                 2.000                 2.000   
2012                    0.023                 2.250                 2.290   
2497                    0.040                 2.100                 2.200   
3199                    0.068                 1.980                 2.300   
...                       ...                   ...                   ...   
106664                  0.147                 3.347                 3.699   
106666                  0.295                 3.049                 3.890   
106811                  0.005                 3.290                 3.299   
106813                  0.100                 3.495                 3.699   
106815                  0.000                 3.290                 3.290   

        MARGEM MÉDIA REVENDA  COEF DE VARIAÇÃO REVENDA  \
1903                     NaN                     0.167   
1958                     NaN                     0.000   
2012                     NaN                     0.010   
2497                     NaN                     0.018   
3199                     NaN                     0.030   
...                      ...                       ...   
106664                   NaN                     0.043   
106666                   NaN                     0.094   
106811                   NaN                     0.002   
106813                   NaN                     0.028   
106815                   NaN                     0.000   

        PREÇO MÉDIO DISTRIBUIÇÃO  DESVIO PADRÃO DISTRIBUIÇÃO  \
1903                        10.0                        20.0   
1958                        10.0                        20.0   
2012                        10.0                        20.0   
2497                        10.0                        20.0   
3199                        10.0                        20.0   
...                          ...                         ...   
106664                      10.0                        20.0   

Por mais que a função `fillna` seja interessante e útil em muitos casos, no problema em questão estamos interessados em analisar precisamente, p. ex., o **'PREÇO MÉDIO DISTRIBUIÇÃO'**.</br>
A fim de não termos valores sintéticos gerados pelo `fillna`, que possam atrapalhar nossa análise, iremos **remover (drop) todas as amostras que possuem qualquer valor NaN** para quaisquer atributos/colunas.

Para isso, basta utilizarmos o método `dropna`.

In [190]:
# Remove no próprio df, todas as linhas/registros com valores NaN (vazios) em quaisquer colunas/atributos
data_pre.dropna(inplace=True)

In [191]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 103392 entries, 0 to 106822
Data columns (total 20 columns):
 #   Column                         Non-Null Count   Dtype         
---  ------                         --------------   -----         
 0   DATA INICIAL                   103392 non-null  datetime64[ns]
 1   DATA FINAL                     103392 non-null  datetime64[ns]
 2   REGIÃO                         103392 non-null  object        
 3   ESTADO                         103392 non-null  object        
 4   PRODUTO                        103392 non-null  object        
 5   NÚMERO DE POSTOS PESQUISADOS   103392 non-null  int64         
 6   UNIDADE DE MEDIDA              103392 non-null  object        
 7   PREÇO MÉDIO REVENDA            103392 non-null  float64       
 8   DESVIO PADRÃO REVENDA          103392 non-null  float64       
 9   PREÇO MÍNIMO REVENDA           103392 non-null  float64       
 10  PREÇO MÁXIMO REVENDA           103392 non-null  float64       
 11  

Nosso data frame agora, após essa limpeza, ficou mais enxuto, contentdo 103392 registros frente aos 106823 registros originais.

Essas são apenas algumas das possíveis técnicas de limpeza de dados. Outras estratégias, p. ex., **confiam na detecção de outliers**, que não veremos neste curso.

**Salvando o Dataset Preprocessado**

In [ ]:
data_pre.to_csv('./datasets/Preco_Combustiveis_preprocessado_final.csv')

### 3. Estatísticas Descritivas

O Pandas fornecem algumas funções/métodos ue computam certas estatísticas descritivas.

`describe`: exibe várias **estatísticas descritivas** para os atributos de um dataframe ou para uma Series.

Como o resultado do `describe` de um dataframe é outro _dataframe_, podemos filtrar apenas algumas colunas.

**Acessando apenas algumas estatísticas**


`mean`, `std`, `min`, etc: cada uma das estatísticas do `describe` podem ser computadas individualmente:

**Qual é o menor preço mínimo de revenda?**

**Qual é a média e desvio padrão dos preços mínimos de revenda?**

**Quais são os estados considerados?**

**Quantos registros (aferições) cada estado possui?**</br>
`.value_counts()`: Conta a frequência dos valores de uma dada variável (de preferência, categórica).

### 4. Executando funções para cada item de um DataFrame ou Series

Uma alternativa ao `for-loop` que vimos anteriormente e que é lento, é usarmos funções próprias do pandas que **aplicam/mapeiam uma dada função a todos os elementos de um DataFrame ou Series**, retornando novos elementos "transformados".

![imagem02](apply_map_applymap.png)

`apply()`: usado para aplicar uma função ao longo de um eixo de um DataFrame ou em valores de uma Series.

![imagem03](imagem03.jpg)

![imagem04](imagem04.png)

![imagem05](imagem05.png)

![iamgem06](imagem06.png)


`applymap()`: usado para aplicar uma função para cada elemento _(element-wise)_ de um DataFrame.

`map()`: usado para aplicar uma função para cada elemento _(element-wise)_ de uma Series.

### 5. Agrupamento

`groupby`: Usado para criar **grupo de elementos** (e.x., baseado nos valores de um atributo).
**Funções** podem então ser aplicadas para os elementos de cada grupo, de modo que os **resultados de cada grupo são combinados**.


Também podemos ter agrupamentos por mais de um atributo.

`.agg`: **agrega (roda)** uma série de funções para os elementos de um dataframe ou de grupos de um dataframe.

### 6. Ordenação

`.sort_values()`: ordena valores ao longo de um eixo.

Por padrão, o método retorna uma cópia dos dados ordenados em **ordem crescente (ascendente)**. Podemos alterar isso pelo argumento `ascending`.

Podemos ordenar a partir de **mais de uma coluna**:

Ordena os registros, primeiramente, pela coluna 'nota_final' em **ordem descrente**.
Então, reordena os registros "empatados", ou seja, com a **mesma nota final**, em ordem alfabética (ordem crescente).

Note que o dataframe original não **foi alterado** após a ordenação.

Para alterá-lo, use o argumento `inplace=True`:

### 7. Exercícios

Vamos aplicar os conceitos que vimos em alguns exercícios.
Para isso, utilizaremos o dataset de preços de combustíveis no Brasil.

Como há apenas medições de janeiro a junho para o ano de 2019, resolvemos **remover os dados** deste ano da análise.

Note que temos um novo dataframe com 99739 linhas, mas com índices fora desse intervalo.</br>
Acontece que os registros mantiveram seus índices originais após a query.

Para resetar os índices de 0 a num_linhas-1, basta usarmos o método `.reset_index()`.

Os índices agora foram resetados. Porém, os índices antigos se transformaram em uma nova coluna chamada 'index'.</br>
Para removê-la durante o reset, basta passarmos o argumento `drop=True`.

**7.1 Qual a proporção de postos pesquisados para cada combustível em cada região**

**7.2 Como os preços da Gasolina Comum em São Paulo variaram em 2018?**

**Estatísticas Descritivas**

**7.3 Como os preços da Gasolina Comum e do Etanol em São Paulo variaram em 2018?**

### 8. Assuntos para continuar os estudos

- join
- concat
- plot
- data cleaning